"use client";
/* eslint-disable @next/next/no-img-element -- imported product images use arbitrary marketplace hosts */

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { attachSheetImageUrls, imageFromRow } from "./import-images";
import { DataStatus, Grade, dataStatusFor, dataWarningFor, gradeLabels, gradeOrder } from "./recommendation-grade";
import { potentialReasons } from "./product-potential";
import { OpportunityTrack } from "./opportunity-track";
import { diversifyOpportunityRows, opportunityFamilyCount } from "./opportunity-diversity";
import { auditProductPlacements, classifyFormalProduct, type PlacementAudit, type ProductPlacement, type ProductOrigin } from "./product-placement";
import { chineseTitleFromRow, furnitureTitleZh } from "./title-translation";
import { fullTitleZh } from "./full-title-translations";
import AcquisitionGuide from "./acquisition-guide";
import GarbageBin from "./garbage-bin";
import BatchCalibrationPanel from "./batch-calibration-panel";
import { BatchCalibrationCandidate } from "./batch-calibration";

type Risk = "低" | "中" | "高";
type OpportunityView = "all" | Exclude<OpportunityTrack, "unmatched">;
type Product = { asin:string; title:string; titleZh?:string; category:string; price:number; rating:number; reviews:number; bsr:number; dimensions:string; weight:number; material:string; variants:string; sellingPoints:string; painPoints:string; sourceUrl:string; imageUrl?:string; importedAt?:string; note:string; complexity:number; differentiation:number; returnRisk:Risk; monthlySales?:number; monthlySalesEstimate?:{min:number;max:number;confidence?:string;source?:string}; launchDays?:number; salesGrowth?:number; packageGrossKg?:number; packageDimensionsCm?:string; estimatedMargin?:number; priceUplift?:number };
declare global { interface Window { __LINX_DATA__?: { products:Product[]; trash:Product[] } } }
const fields: (keyof Product)[] = ["asin","title","titleZh","imageUrl","importedAt","category","price","monthlySales","launchDays","salesGrowth","estimatedMargin","packageGrossKg","packageDimensionsCm","priceUplift","rating","reviews","bsr","dimensions","weight","material","variants","sellingPoints","painPoints","sourceUrl","note","complexity","differentiation","returnRisk"];
const labels: Record<keyof Product,string> = { asin:"ASIN",title:"英文标题",titleZh:"中文标题",imageUrl:"商品主图链接",importedAt:"导入时间",category:"类目",price:"价格(USD)",monthlySales:"月销量",launchDays:"上架天数",salesGrowth:"销量环比增长率",estimatedMargin:"已报价利润率(可选覆盖)",packageGrossKg:"单箱包装毛重(kg)",packageDimensionsCm:"包装尺寸(cm)",priceUplift:"改款提价潜力(可选覆盖)",rating:"评分",reviews:"评论数",bsr:"BSR",dimensions:"尺寸",weight:"重量(lb)",material:"材质",variants:"颜色/变体",sellingPoints:"卖点",painPoints:"差评痛点",sourceUrl:"来源链接",note:"中文备注",complexity:"结构复杂度(1-5)",differentiation:"差异化空间(1-5)",returnRisk:"退货风险" };
async function builtInProducts(){if(window.__LINX_DATA__)return window.__LINX_DATA__;const[productsResponse,trashResponse]=await Promise.all([fetch("/real-products.json"),fetch("/rejected-products.json")]);if(!productsResponse.ok||!trashResponse.ok)throw Error("built-in product data unavailable");return{products:await productsResponse.json() as Product[],trash:await trashResponse.json() as Product[]}}
function compute(p:Product,placement:ProductPlacement){
 const company={...placement.assessment,categoryVerdict:placement.opportunityTrackLabel?`${placement.opportunityTrackLabel} · ${placement.reasons.at(-1)??"已完成统一归位"}`:"垃圾箱 · 已触发硬性淘汰"};
 const dev=company.companyFit;
 const diff=Math.round((company.hiddenOpportunity*.7)+(Math.min(5,Math.max(1,p.differentiation))*20*.3));
 const market=company.demand;
 const risk=company.hardRejected?0:100;
 const total=company.score;
 return{dev,diff,market,risk,total,reasons:company.reasons,company};
}
type ScoredProduct = Product&{score:ReturnType<typeof compute>;placement:ProductPlacement};
const compact=(value:number)=>value>0?new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:1}).format(value):"—";
const monthlySalesValue=(product:Product)=>Number(product.monthlySales??0)>0?Number(product.monthlySales):(product.monthlySalesEstimate?(product.monthlySalesEstimate.min+product.monthlySalesEstimate.max)/2:0);
const monthlySalesLabel=(product:Product)=>Number(product.monthlySales??0)>0?compact(Number(product.monthlySales)):product.monthlySalesEstimate?`${compact(product.monthlySalesEstimate.min)}–${compact(product.monthlySalesEstimate.max)}`:"—";
const withUnit=(value:number|undefined,unit:string)=>Number(value)>0?`${value} ${unit}`:"—";
const percent=(value:number|undefined)=>{const number=Number(value||0);return`${(Math.abs(number)<=2?number*100:number).toFixed(1)}%`};
const dataContext=(product:Product)=>({category:product.category,material:product.material,price:product.price});
const dataStatus=(product:Product):DataStatus=>dataStatusFor(product.packageDimensionsCm,product.packageGrossKg,dataContext(product));
const dataWarning=(product:Product)=>dataWarningFor(product.packageDimensionsCm,product.packageGrossKg,dataContext(product));
const gradeOf=(product:ScoredProduct):Grade=>product.placement.grade;
const interestOrder={priority:0,unrated:1,normal:1,low:2} as const;
const recommendationOrder=(a:ScoredProduct,b:ScoredProduct)=>interestOrder[a.score.company.interestTier]-interestOrder[b.score.company.interestTier]||gradeOrder[gradeOf(a)]-gradeOrder[gradeOf(b)]||b.score.total-a.score.total;
const gradeConclusion=(product:ScoredProduct)=>`${gradeOf(product)} · ${gradeLabels[gradeOf(product)]}`;
const formatImportedAt=(value:string|undefined)=>value?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"}).format(new Date(value)):"历史数据";
function saveFile(name:string,content:string,type="text/plain;charset=utf-8"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function blank():Product{return{asin:"",title:"",titleZh:"",imageUrl:"",importedAt:new Date().toISOString(),category:"客厅 / 边几",price:0,rating:0,reviews:0,bsr:99999,dimensions:"",weight:0,material:"",variants:"",sellingPoints:"",painPoints:"",sourceUrl:"",note:"",complexity:3,differentiation:3,returnRisk:"中"}}
function num(v:unknown){const match=String(v??"").replace(/,/g,"").match(/-?\d+(?:\.\d+)?/);return Number(match?.[0])||0}
function margin(v:unknown){const value=num(v);return value>0&&value<=1?value*100:value}
function sellerProduct(r:Record<string,unknown>):Product { const text=(v:unknown)=>String(v??""); const packageKg=num(r["包装重量（单位换算）"]); const title=text(r["商品标题"]); return {asin:text(r.ASIN),title,titleZh:chineseTitleFromRow(r),imageUrl:imageFromRow(r),importedAt:new Date().toISOString(),category:text(r["小类目"]||r["类目路径"]),price:num(r["价格($)"]),monthlySales:num(r["月销量"]),launchDays:num(r["上架天数"]),salesGrowth:num(r["销量环比增长率"]),packageGrossKg:packageKg,packageDimensionsCm:text(r["包装尺寸（单位换算）"]),rating:num(r["评分"]),reviews:num(r["评分数"]),bsr:num(r["小类BSR"]),dimensions:text(r["商品尺寸（单位换算）"]),weight:packageKg*2.205,material:text(r["详细参数"]),variants:text(r.SKU),sellingPoints:text(r["标签"]),painPoints:"",sourceUrl:text(r["商品详情页链接"]),note:text(r["品牌"]),complexity:3,differentiation:3,returnRisk:packageKg>49?"高":packageKg>22?"中":"低",estimatedMargin:margin(r["毛利率"]),priceUplift:3}; }

export default function Home(){
 const [tab,setTab]=useState("机会筛选"),[products,setProducts]=useState<Product[]>([]),[trash,setTrash]=useState<Product[]>([]),[editing,setEditing]=useState<Product|null>(null),[notice,setNotice]=useState("");
 const [favorites,setFavorites]=useState<Set<string>>(new Set()),[selected,setSelected]=useState<Set<string>>(new Set()),[hydrated,setHydrated]=useState(false),[compareOpen,setCompareOpen]=useState(false),[importMode,setImportMode]=useState<"replace"|"merge">("replace"),[opportunityTrack,setOpportunityTrack]=useState<OpportunityView>("all");
 const baselineProducts=useRef(new Map<string,Product>()),baselineTrash=useRef(new Map<string,Product>());
 const [filters,setFilters]=useState({search:"",category:"全部",grade:"全部",minSales:0,sort:"grade"});
 useEffect(()=>{const id=window.setTimeout(()=>{if(new URLSearchParams(window.location.search).get("tab")==="calibration")setTab("校准模式")},0);return()=>window.clearTimeout(id)},[]);
 // Compatibility for the former D-list navigation target.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(tab==="不推荐")setTab("垃圾箱")},[tab]);
 // Built-in pools are static assets so large imports do not make the Sites compiler parse megabytes of JSON repeatedly.
 useEffect(()=>{let cancelled=false;const id=window.setTimeout(()=>{void(async()=>{try{localStorage.removeItem("furniture-radar-v2");localStorage.removeItem("furniture-radar-v3");const builtIn=await builtInProducts();if(cancelled)return;baselineProducts.current=new Map(builtIn.products.map(p=>[p.asin,p]));baselineTrash.current=new Map(builtIn.trash.map(p=>[p.asin,p]));const productMap=new Map(baselineProducts.current),trashMap=new Map(baselineTrash.current);const raw=localStorage.getItem("furniture-radar-v6")||localStorage.getItem("furniture-radar-v5")||localStorage.getItem("furniture-radar-v4");if(raw)try{const d=JSON.parse(raw);if(Array.isArray(d.productOverrides)){d.productOverrides.forEach((p:Product)=>productMap.set(p.asin,p));d.trashOverrides?.forEach((p:Product)=>trashMap.set(p.asin,p));d.deletedProducts?.forEach((asin:string)=>productMap.delete(asin));d.deletedTrash?.forEach((asin:string)=>trashMap.delete(asin))}else{d.products?.forEach((p:Product)=>productMap.set(p.asin,p));d.trash?.forEach((p:Product)=>trashMap.set(p.asin,p))}setFavorites(new Set(d.favorites??[]))}catch{}setProducts([...productMap.values()]);setTrash([...trashMap.values()])}catch{if(!cancelled)setNotice("内置产品数据加载失败，请刷新页面重试。")}finally{if(!cancelled)setHydrated(true)}})()},0);return()=>{cancelled=true;window.clearTimeout(id)}},[]);
 useEffect(()=>{if(!hydrated)return;const productMap=new Map(products.map(p=>[p.asin,p])),trashMap=new Map(trash.map(p=>[p.asin,p]));const productOverrides=products.filter(p=>JSON.stringify(baselineProducts.current.get(p.asin))!==JSON.stringify(p));const trashOverrides=trash.filter(p=>JSON.stringify(baselineTrash.current.get(p.asin))!==JSON.stringify(p));const deletedProducts=[...baselineProducts.current.keys()].filter(asin=>!productMap.has(asin));const deletedTrash=[...baselineTrash.current.keys()].filter(asin=>!trashMap.has(asin));try{localStorage.setItem("furniture-radar-v6",JSON.stringify({productOverrides,trashOverrides,deletedProducts,deletedTrash,favorites:[...favorites]}));localStorage.removeItem("furniture-radar-v5");localStorage.removeItem("furniture-radar-v4")}catch{window.setTimeout(()=>setNotice("本机存储空间不足，请下载 JSON 备份保存本次修改。"),0)}},[products,trash,favorites,hydrated]);
 const formalProducts=useMemo<Product[]>(()=>[...new Map(products.map(product=>[product.asin,product])).values()],[products]);
 const scoredProducts=useMemo<ScoredProduct[]>(()=>formalProducts.map(p=>{const origin:ProductOrigin=p.importedAt?"import":"historical";const placement=classifyFormalProduct({...p,manualFavorite:favorites.has(p.asin)},origin);return{...p,placement,score:compute(p,placement)}}),[formalProducts,favorites]);
 const scoredTrash=useMemo<ScoredProduct[]>(()=>trash.map(p=>{const placement=classifyFormalProduct({...p,manualFavorite:false},"real-products");return{...p,placement,score:compute(p,placement)}}),[trash]);
 const placementAudit=useMemo(()=>auditProductPlacements(scoredProducts.map(p=>p.placement)),[scoredProducts]);
 const calibrationProducts=useMemo<BatchCalibrationCandidate[]>(()=>scoredProducts.filter(p=>p.placement.destination!=="garbage").map(p=>({asin:p.asin,title:p.title,titleZh:fullTitleZh(p.asin,p.titleZh),category:p.category,grade:gradeOf(p),score:p.score.total,interestTier:p.score.company.interestTier,imageUrl:p.imageUrl,sourceUrl:productUrl(p),price:p.price,monthlySales:p.monthlySales??0,reasons:p.score.reasons})),[scoredProducts]);
 const rows=useMemo(()=>scoredProducts.filter(p=>(filters.category==="全部"||p.category===filters.category)&&(filters.grade==="全部"||gradeOf(p)===filters.grade)&&monthlySalesValue(p)>=filters.minSales&&`${p.asin} ${p.title} ${fullTitleZh(p.asin,p.titleZh)}`.toLowerCase().includes(filters.search.toLowerCase())).sort((a,b)=>filters.sort==="sales"?monthlySalesValue(b)-monthlySalesValue(a):filters.sort==="growth"?(b.salesGrowth??0)-(a.salesGrowth??0):filters.sort==="margin"?b.score.company.estimatedMargin-a.score.company.estimatedMargin:recommendationOrder(a,b)),[scoredProducts,filters]);
 const recommended=useMemo(()=>scoredProducts.filter(p=>gradeOf(p)==="A"||gradeOf(p)==="B").sort(recommendationOrder),[scoredProducts]);
 const gradeCounts=placementAudit.grades;
 const dataPendingRows=useMemo(()=>scoredProducts.filter(p=>p.placement.needsData&&p.placement.destination!=="garbage").sort((a,b)=>b.score.company.demand-a.score.company.demand),[scoredProducts]);
 const trackCounts=useMemo<Record<OpportunityTrack,number>>(()=>({"red-ocean-blue":placementAudit.destinations["red-ocean-blue"],"blue-ocean-red":placementAudit.destinations["blue-ocean-red"],unmatched:placementAudit.destinations.unmatched}),[placementAudit]);
 const opportunityMatchedRows=useMemo(()=>scoredProducts.filter(p=>p.placement.destination==="red-ocean-blue"||p.placement.destination==="blue-ocean-red"),[scoredProducts]);
 const opportunityBase=useMemo(()=>rows.filter(p=>{if(p.placement.destination==="garbage")return false;if(filters.grade!=="全部")return true;return(p.placement.destination==="red-ocean-blue"||p.placement.destination==="blue-ocean-red")&&(opportunityTrack==="all"||p.placement.destination===opportunityTrack)}).sort(recommendationOrder),[rows,filters.grade,opportunityTrack]);
 const opportunityRows=useMemo(()=>diversifyOpportunityRows(opportunityBase),[opportunityBase]);
 const familyCount=useMemo(()=>opportunityFamilyCount(opportunityBase),[opportunityBase]);
 const unmatchedRows=useMemo(()=>scoredProducts.filter(p=>p.placement.destination==="unmatched").sort(recommendationOrder),[scoredProducts]);
 const rejectedRows=useMemo(()=>[...scoredProducts,...scoredTrash].filter(p=>p.placement.destination==="garbage").sort((a,b)=>b.score.company.demand-a.score.company.demand),[scoredProducts,scoredTrash]);
 const garbageRows=useMemo(()=>rejectedRows.map(({score,placement,...product})=>{void score;void placement;return product}),[rejectedRows]);
 const rescuedTrashRows=useMemo(()=>scoredTrash.filter(p=>p.placement.destination!=="garbage"),[scoredTrash]);
 const potentialRows=useMemo(()=>scoredProducts.filter(p=>p.placement.potential&&p.placement.destination!=="garbage").sort((a,b)=>potentialReasons(b).length-potentialReasons(a).length||b.score.total-a.score.total),[scoredProducts]);
 const favoriteRows=useMemo(()=>scoredProducts.filter(p=>p.placement.favorite&&p.placement.destination!=="garbage").sort(recommendationOrder),[scoredProducts]);
 const selectedRows=useMemo(()=>scoredProducts.filter(p=>selected.has(p.asin)),[scoredProducts,selected]);
 const cats=["全部",...Array.from(new Set(products.map(p=>p.category)))];
 const exportXlsx=async(output:ScoredProduct[],name="家具选品候选ASIN")=>{const XLSX=await import("xlsx");const header=[...fields.map(f=>labels[f]),"推荐等级","推荐结论","主归位","数据状态","潜力款","预估利润率","利润可信度","风险与提示","已收藏"];const data=[header,...output.map(p=>[...fields.map(f=>p[f]),gradeOf(p),gradeLabels[gradeOf(p)],p.placement.opportunityTrackLabel??"垃圾箱",p.placement.needsData?"数据待补":"数据完整",p.placement.potential?"是":"否",p.score.company.estimatedMargin,p.score.company.marginConfidence,[dataWarning(p),...p.placement.reasons].filter(Boolean).join("；"),p.placement.favorite?"是":"否"])];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(data),"选品清单");XLSX.writeFile(book,`${name}.xlsx`)};
 const exportCsv=(output:ScoredProduct[],name="家具选品清单")=>saveFile(`${name}.csv`,[[...fields.map(f=>labels[f]),"推荐等级","推荐结论","主归位","数据状态"].join(","),...output.map(p=>[...fields.map(f=>p[f]),gradeOf(p),gradeLabels[gradeOf(p)],p.placement.opportunityTrackLabel??"垃圾箱",p.placement.needsData?"数据待补":"数据完整"].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(","))].join("\n"),"text/csv;charset=utf-8");
 const toggleFavorite=(asin:string)=>setFavorites(old=>{const next=new Set(old);if(next.has(asin))next.delete(asin);else next.add(asin);return next});
 const toggleSelected=(asin:string)=>setSelected(old=>{const next=new Set(old);if(next.has(asin))next.delete(asin);else next.add(asin);return next});
 const selectVisible=(data:Product[],checked:boolean)=>setSelected(old=>{const next=new Set(old);data.forEach(p=>checked?next.add(p.asin):next.delete(p.asin));return next});
 const favoriteSelected=()=>{setFavorites(old=>new Set([...old,...selected]));setNotice(`已收藏 ${selected.size} 个产品。`)};
 const removeProducts=(asins:Set<string>)=>{if(!asins.size||!window.confirm(`确定删除 ${asins.size} 条产品记录吗？此操作无法撤销。`))return;setProducts(old=>old.filter(p=>!asins.has(p.asin)));setFavorites(old=>new Set([...old].filter(x=>!asins.has(x))));setSelected(old=>new Set([...old].filter(x=>!asins.has(x))));setNotice(`已删除 ${asins.size} 条记录。`)};
 // Auto-route confirmed hard rejects out of the active collection.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!hydrated||!rejectedRows.length)return;const activeAsins=new Set(products.map(p=>p.asin));const activeRejected=rejectedRows.filter(p=>activeAsins.has(p.asin));if(!activeRejected.length)return;const rejectedAsins=new Set(activeRejected.map(p=>p.asin));setProducts(old=>old.filter(p=>!rejectedAsins.has(p.asin)));setTrash(old=>{const merged=new Map(old.map(p=>[p.asin,p]));activeRejected.forEach(item=>{const {score,placement,...product}=item;void score;void placement;merged.set(product.asin,product)});return[...merged.values()]});setFavorites(old=>new Set([...old].filter(x=>!rejectedAsins.has(x))));setSelected(old=>new Set([...old].filter(x=>!rejectedAsins.has(x))))},[rejectedRows,hydrated,products]);
 // Auto-return historical trash items that no longer match a hard D rule.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(!hydrated||!rescuedTrashRows.length)return;const rescuedAsins=new Set(rescuedTrashRows.map(p=>p.asin));setTrash(old=>old.filter(p=>!rescuedAsins.has(p.asin)));setProducts(old=>{const merged=new Map(old.map(p=>[p.asin,p]));rescuedTrashRows.forEach(item=>{const {score,placement,...product}=item;void score;void placement;merged.set(product.asin,product)});return[...merged.values()]})},[hydrated,rescuedTrashRows]);
 const restoreFromTrash=(product:Product)=>{setTrash(old=>old.filter(p=>p.asin!==product.asin));setEditing(product);setTab("数据管理");setNotice("已从垃圾箱取出，请修改导致淘汰的字段后保存；若仍触发硬性条件会再次回到垃圾箱。");};
 const emptyTrash=()=>{if(!trash.length||!window.confirm(`确定永久删除垃圾箱中的 ${trash.length} 条记录吗？`))return;setTrash([]);setNotice("垃圾箱已清空。");};
 const downloadTemplate=async()=>{const XLSX=await import("xlsx");const b=XLSX.utils.book_new();const sample=products[0]??blank();XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([fields.map(f=>labels[f]),fields.map(f=>sample[f])]),"竞品数据");XLSX.writeFile(b,"家具选品导入模板.xlsx")};
 const importProducts=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer());const sheet=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});attachSheetImageUrls(sheet,raw,XLSX);const isSellerSprite=Object.prototype.hasOwnProperty.call(raw[0]??{},"商品标题");const importedAt=new Date().toISOString();const incoming=(isSellerSprite?raw.map(sellerProduct):raw.map(r=>Object.fromEntries(fields.map(f=>[f,f==="imageUrl"?imageFromRow(r):r[labels[f]]??r[f]??""])) as unknown as Product)).filter(p=>p.asin&&p.title).map(p=>({...p,titleZh:String(p.titleZh||furnitureTitleZh(p.title)),importedAt,price:Number(p.price)||0,rating:Number(p.rating)||0,reviews:Number(p.reviews)||0,bsr:Number(p.bsr)||99999,weight:Number(p.weight)||0,monthlySales:Number(p.monthlySales)||0,launchDays:Number(p.launchDays)||9999,salesGrowth:Number(p.salesGrowth)||0,packageGrossKg:Number(p.packageGrossKg)||0,estimatedMargin:margin(p.estimatedMargin),priceUplift:Number(p.priceUplift)||3,complexity:Number(p.complexity)||3,differentiation:Number(p.differentiation)||3,returnRisk:["低","中","高"].includes(String(p.returnRisk))?p.returnRisk:"中" as Risk}));if(!incoming.length)throw Error();const imageCount=incoming.filter(p=>p.imageUrl).length;if(importMode==="replace"){if(!window.confirm(`将用 ${incoming.length} 条新数据替换当前 ${products.length} 条产品，收藏和已选记录也会清空。确定继续吗？`))return;setProducts(incoming);setFavorites(new Set());setSelected(new Set())}else setProducts(old=>{const map=new Map(old.map(p=>[p.asin,p]));incoming.forEach(p=>map.set(p.asin,p));return[...map.values()]});setNotice(`已${importMode==="replace"?"替换为":"追加"} ${incoming.length} 条产品，其中自动识别主图 ${imageCount} 张，导入时间 ${formatImportedAt(importedAt)}。`)}catch{setNotice("导入失败：请使用模板列名，并确认 ASIN 和英文标题已填写。")}finally{e.target.value=""}};
 const save=()=>{if(!editing?.asin||!editing.title)return setNotice("请至少填写 ASIN 和英文标题。");setProducts(old=>{const i=old.findIndex(p=>p.asin===editing.asin);return i<0?[editing,...old]:old.map((p,n)=>n===i?editing:p)});setTrash(old=>old.filter(p=>p.asin!==editing.asin));setEditing(null);setNotice("记录已保存，并已按统一条件重新归位。")};
 return <><main><header><div><span className="eyebrow">AI PRODUCT INTELLIGENCE · AMAZON US</span><h1 className="brand">LIN<span>X</span></h1><p>家具机会识别工作台 · {placementAudit.total} 个正式 ASIN，历史与新增产品均按同一套条件自动归位。</p></div><div className="header-score"><b>{opportunityMatchedRows.length}</b><span>个进入初筛排名（两条机会线）</span></div></header>
 <nav>{["机会筛选","方向不匹配","校准模式","潜力款","候选 ASIN","数据待补","垃圾箱","采集逻辑","数据管理","收藏夹","推荐规则"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}{x==="方向不匹配"&&unmatchedRows.length>0?<em>{unmatchedRows.length}</em>:x==="校准模式"?<em>批量</em>:x==="潜力款"&&potentialRows.length>0?<em>{potentialRows.length}</em>:x==="数据待补"&&dataPendingRows.length>0?<em>{dataPendingRows.length}</em>:x==="垃圾箱"&&garbageRows.length>0?<em>{garbageRows.length}</em>:x==="收藏夹"&&placementAudit.labels.favorite>0?<em>{placementAudit.labels.favorite}</em>:null}</button>)}</nav>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 {tab==="机会筛选"&&<><section className="hero"><div><span className="tag">DUAL OPPORTUNITY MODEL</span><h2>两条开发赛道 · 全量自动归位</h2><p>历史与每天新增的正式产品都会进入统一分类。每日最多300款只是采集入库上限，不是保证新增数量；每个位置没有容量限制，也不会只截取 Top N。</p><div className="pool-summary"><span><b>{placementAudit.total}</b><small>正式产品池总数</small></span><span><b>{opportunityMatchedRows.length}</b><small>符合两条机会线</small></span><span><b>{unmatchedRows.length}</b><small>方向不匹配</small></span><span><b>{garbageRows.length}</b><small>D级垃圾箱</small></span></div><small>当前筛选视图：{opportunityRows.length} 款 · {familyCount} 个产品家族 · {placementAudit.valid?"全部产品主归位校验通过":"归位校验异常，请暂停使用"}</small></div><div className="grade-summary">{(["A","B","C","D"] as Grade[]).map(grade=><button key={grade} onClick={()=>grade==="D"?setTab("垃圾箱"):setFilters({...filters,grade})}><b className={`grade grade-${grade}`}>{grade}</b><span>{gradeLabels[grade]} · {gradeCounts[grade]} 个</span></button>)}</div></section><PlacementSummary audit={placementAudit}/><OpportunityTracks active={opportunityTrack} setActive={setOpportunityTrack} counts={trackCounts}/><section className="filters"><input placeholder="搜索 ASIN 或英文标题" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select><select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value})}>{["全部","A","B","C"].map(x=><option key={x}>{x==="全部"?"全部推荐等级":`${x} · ${gradeLabels[x as Grade]}`}</option>)}</select><label>最低月销 <input type="number" value={filters.minSales||""} placeholder="不限" onChange={e=>setFilters({...filters,minSales:Number(e.target.value)||0})}/></label><select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="grade">统一推荐顺序</option><option value="sales">月销量排序</option><option value="growth">增长率排序</option><option value="margin">利润率排序</option></select><button className="quiet" onClick={()=>setFilters({search:"",category:"全部",grade:"全部",minSales:0,sort:"grade"})}>重置</button></section><BulkBar data={opportunityRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Cards rows={opportunityRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></>}
  {tab==="方向不匹配"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">OUTSIDE CURRENT STRATEGY</span><h2>方向不匹配</h2><p>这些产品没有触发硬性淘汰，但目前既缺少成熟柜类的明确造型创新，也没有足够清晰的小众使用场景，因此不进入两条机会榜。</p></div><span className="tag">{unmatchedRows.length} 个</span></div><Cards rows={unmatchedRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
  {tab==="校准模式"&&<BatchCalibrationPanel products={calibrationProducts}/>}
 {tab==="潜力款"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">EARLY OPPORTUNITIES</span><h2>潜力款</h2><p>上架不超过 180 天、月销 50–300、单 Listing 评论少于 100，并出现增长、造型或改款信号；月销超过 300 已属于爆款。</p></div><span className="tag">{potentialRows.length} 个潜力信号</span></div><BulkBar data={potentialRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"潜力款已选")} compare={()=>setCompareOpen(true)}/><Cards rows={potentialRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="数据待补"&&<section className="panel data-pending-panel"><div className="section-title"><div><span className="eyebrow">DATA REQUIRED</span><h2>数据待补</h2><p>缺少包装、材质、销量或上架时间只影响数据可信度，不再把所有商品强制压成 C，也不会因为缺数据判 D；A / B / C / D 与数据状态分开显示。</p></div><span className="tag">{dataPendingRows.length} 个待补记录</span></div><BulkBar data={dataPendingRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"数据待补产品")} compare={()=>setCompareOpen(true)}/><Cards rows={dataPendingRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="数据管理"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">DATA INTAKE</span><h2>竞品数据管理</h2><p>当前为亚马逊美国站自主调研的 {products.length} 个不重复 ASIN，主图与 Listing 链接完整。</p></div><div className="actions"><select value={importMode} onChange={e=>setImportMode(e.target.value as "replace"|"merge")}><option value="replace">导入后替换当前批次</option><option value="merge">追加并更新重复 ASIN</option></select><button onClick={downloadTemplate}>下载 XLSX 模板</button><label className="primary file">导入 CSV / XLSX<input type="file" accept=".csv,.xlsx,.xls" onChange={importProducts}/></label><button onClick={()=>setEditing(blank())}>+ 新增记录</button></div></div>{editing?<Form product={editing} set={setEditing} save={save} cancel={()=>setEditing(null)}/>:<><BulkBar data={products} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)} removeSelected={()=>removeProducts(selected)}/><Table data={products} edit={setEditing} remove={asin=>removeProducts(new Set([asin]))} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></>}</section>}
 {tab==="候选 ASIN"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">SHORTLIST</span><h2>候选 ASIN 清单</h2><p>仅显示通过公司适配、物流与利润预测筛选的记录。</p></div><div className="actions"><button onClick={()=>exportCsv(selectedRows.length?selectedRows:recommended,"家具选品候选ASIN")}>导出 CSV</button><button className="primary" onClick={()=>exportXlsx(selectedRows.length?selectedRows:recommended)}>导出 Excel</button></div></div><BulkBar data={recommended} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Table data={recommended} edit={p=>{setEditing(p);setTab("数据管理")}} remove={()=>{}} showScore selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="垃圾箱"&&<GarbageBin products={garbageRows} restore={p=>restoreFromTrash(p as Product)} empty={emptyTrash}/>}
 {tab==="采集逻辑"&&<AcquisitionGuide formalPoolCount={placementAudit.total} placementAudit={placementAudit}/>}
 {tab==="收藏夹"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">FAVORITES</span><h2>产品收藏夹</h2><p>红心产品会一直保存在当前浏览器，可多选比较或导出。</p></div><button className="primary" disabled={!favoriteRows.length} onClick={()=>exportXlsx(favoriteRows,"收藏产品")}>导出收藏</button></div><BulkBar data={favoriteRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Cards rows={favoriteRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="推荐规则"&&<Settings products={products} setProducts={setProducts} favorites={favorites} setFavorites={setFavorites} notice={setNotice}/>}</main>
 {compareOpen&&<CompareDrawer products={selectedRows.slice(0,4)} close={()=>setCompareOpen(false)}/>}
 </>;
}
function BulkBar({data,selected,selectVisible,favoriteSelected,exportSelected,compare,removeSelected}:{data:Product[];selected:Set<string>;selectVisible:(data:Product[],checked:boolean)=>void;favoriteSelected:()=>void;exportSelected:()=>void;compare:()=>void;removeSelected?:()=>void}){const visibleSelected=data.filter(p=>selected.has(p.asin)).length;const allSelected=data.length>0&&visibleSelected===data.length;return <div className="bulk-bar"><label><input type="checkbox" checked={allSelected} onChange={e=>selectVisible(data,e.target.checked)}/><span>{allSelected?"取消全选":"选择当前结果"}</span></label><span className="result-count">{data.length} 个结果</span>{selected.size>0&&<div className="bulk-actions"><b>已选 {selected.size}</b><button onClick={favoriteSelected}>♥ 批量收藏</button><button onClick={compare}>并排对比</button><button onClick={exportSelected}>导出已选</button>{removeSelected&&<button className="danger-action" onClick={removeSelected}>删除已选</button>}</div>}</div>}
function ProductVisual({product}:{product:Product}){const[failed,setFailed]=useState(false);return <div className="product-visual"><span aria-hidden="true">▱</span>{product.imageUrl&&!failed&&<img src={product.imageUrl} alt={product.title} loading="lazy" onError={()=>setFailed(true)}/>}<small>{failed?"主图暂时无法加载":product.imageUrl?"":"导入主图后显示"}</small></div>}
function productUrl(product:Product){const source=product.sourceUrl?.trim();if(source)return source;return/^[A-Z0-9]{10}$/i.test(product.asin)?`https://www.amazon.com/dp/${product.asin}`:`https://www.amazon.com/s?k=${encodeURIComponent(product.title)}`}
function ProductTitle({product}:{product:Product}){return <><a href={productUrl(product)} target="_blank" rel="noreferrer" title="打开 Amazon Listing">{product.title}<span className="external">↗</span></a><span className="title-zh">{fullTitleZh(product.asin,product.titleZh)}</span></>}
function OpportunityTracks({active,setActive,counts}:{active:OpportunityView;setActive:(track:OpportunityView)=>void;counts:Record<OpportunityTrack,number>}){const tracks:[OpportunityView,string,string,string,number][]=[["all","多类目机会总览","默认交错展示","先跨产品家族查看全部机会，再进入两条赛道分别研究。",counts["red-ocean-blue"]+counts["blue-ocean-red"]],["red-ocean-blue","红海中的蓝海","成熟类目 · 元素造型创新","餐边柜、橱柜、咖啡吧柜、电视柜、斗柜、书架和玄关柜等成熟市场。",counts["red-ocean-blue"]],["blue-ocean-red","蓝海中的红海","小众类目 · 场景功能机会","爬宠箱、洗衣机工作台、美甲桌、商业前台、宠物家具和手作工作台等细分场景。",counts["blue-ocean-red"]]];return <section className="track-switcher">{tracks.map(([id,title,subtitle,description,count])=><button key={id} className={active===id?"active":""} onClick={()=>setActive(id)}><span>{subtitle}</span><b>{title}</b><p>{description}</p><em>{count} 款符合</em></button>)}</section>}
function PlacementSummary({audit}:{audit:PlacementAudit}){const items=[["红海中的蓝海",audit.destinations["red-ocean-blue"]],["蓝海中的红海",audit.destinations["blue-ocean-red"]],["方向不匹配",audit.destinations.unmatched],["D级垃圾箱",audit.destinations.garbage],["潜力款标签",audit.labels.potential],["数据待补标签",audit.labels.needsData],["收藏标签",audit.labels.favorite]] as const;return <section className={`placement-summary ${audit.valid?"is-valid":"is-invalid"}`} aria-label="统一归位真实计数"><div><span className="eyebrow">PLACEMENT AUDIT</span><b>{audit.valid?"主归位校验通过":"主归位校验异常"}</b><small>{audit.traceable}/{audit.total} 个正式产品均可追溯到唯一主归位；潜力、待补和收藏为可重叠标签。</small></div><div className="placement-counts">{items.map(([label,count])=><span key={label}><b>{count}</b><small>{label}</small></span>)}</div>{!audit.valid&&<p>{audit.errors.join("；")}</p>}</section>}
function Cards({rows,edit,selected,favorites,toggleSelected,toggleFavorite}:{rows:ScoredProduct[];edit:(p:Product)=>void;selected:Set<string>;favorites:Set<string>;toggleSelected:(asin:string)=>void;toggleFavorite:(asin:string)=>void}){
 return <section className="cards">{rows.map(p=>{
  const potential=p.placement.potential,warning=p.placement.needsData?(dataWarning(p)||"关键筛选数据待补"):"",grade=gradeOf(p);
  return <article className={`card ${selected.has(p.asin)?"selected":""}`} key={p.asin} tabIndex={0}><div className="card-select"><label title="选择产品"><input type="checkbox" checked={selected.has(p.asin)} onChange={()=>toggleSelected(p.asin)}/></label><button className={`heart ${favorites.has(p.asin)?"active":""}`} onClick={()=>toggleFavorite(p.asin)} aria-label={favorites.has(p.asin)?"取消收藏":"收藏产品"}>♥</button></div><ProductVisual product={p}/><div className="card-body"><div className="card-top"><div className="card-labels">{warning&&<span className="data-status-badge">数据待补</span>}{potential&&<span className="potential-badge">潜力款</span>}</div><strong className={`grade grade-${grade}`}>{grade}<small>{gradeLabels[grade]}</small></strong></div><span className="category">{p.category}</span><h3><ProductTitle product={p}/></h3><p className="asin">ASIN: {p.asin}</p><div className="quick-stats"><div className="price-stat"><b>{p.price>0?`$${p.price}`:"—"}</b><span>售价</span></div><div><b>{monthlySalesLabel(p)}</b><span>月销区间</span></div><div><b>★ {p.rating||"—"}</b><span>{compact(p.reviews)} 条评论</span></div><div><b>{p.bsr>0?`#${compact(p.bsr)}`:"—"}</b><span>类目 BSR</span></div></div><div className="hover-hint">悬停查看更多信息 ↓</div><div className="card-details"><div className="detail-grid"><span><b className={(p.salesGrowth??0)>0?"up":""}>{(p.salesGrowth??0)>0?"+":""}{percent(p.salesGrowth)}</b>销量增长</span><span><b>{percent(p.score.company.estimatedMargin)}</b>预估利润</span><span><b>{withUnit(p.packageGrossKg,"kg")}</b>包装毛重</span><span><b>{withUnit(p.launchDays,"天")}</b>上架时间</span><span><b>{formatImportedAt(p.importedAt)}</b>导入时间</span></div><div className="meter"><i style={{width:p.score.dev+"%"}}/></div><p className="opportunity">{potential?`潜力信号：${potentialReasons(p).join("、")}`:p.score.company.affinity.length?`匹配方向：${p.score.company.affinity.join("、")}`:p.score.company.trendElements.length?`机会元素：${p.score.company.trendElements.join("、")}`:p.note||"待补充改款方向"}</p><p className={warning?"reason data-warning":"reason"}>{warning||(p.score.reasons.length?p.score.reasons.slice(0,2).join(" · "):"物流与开发风险可控")}</p></div><div className="card-bottom"><span>{p.score.company.categoryVerdict}</span><button onClick={()=>edit(p)}>完整数据 →</button></div></div></article>
 })}{!rows.length&&<div className="empty"><b>这里暂时没有产品</b><span>调整筛选条件，或在商品卡上点击红心加入收藏。</span></div>}</section>
}
function Table({data,edit,remove,showScore=false,selected,favorites,toggleSelected,toggleFavorite}:{data:(Product|ScoredProduct)[];edit:(p:Product)=>void;remove:(asin:string)=>void;showScore?:boolean;selected:Set<string>;favorites:Set<string>;toggleSelected:(asin:string)=>void;toggleFavorite:(asin:string)=>void}){return <div className="table-wrap"><table><thead><tr><th className="check-col"></th><th>ASIN / 商品</th><th>类目</th><th>价格</th><th>月销区间</th><th>导入时间</th><th>风险</th><th>数据状态</th>{showScore&&<th>推荐结论</th>}<th>操作</th></tr></thead><tbody>{data.map(p=>{const pending="placement" in p?p.placement.needsData:dataStatus(p)==="needs_data";return <tr key={p.asin} className={selected.has(p.asin)?"selected-row":""}><td><input type="checkbox" checked={selected.has(p.asin)} onChange={()=>toggleSelected(p.asin)}/></td><td><div className="table-product"><button className={`heart ${favorites.has(p.asin)?"active":""}`} onClick={()=>toggleFavorite(p.asin)}>♥</button><div><b>{p.asin}</b><span><ProductTitle product={p}/></span></div></div></td><td>{p.category}</td><td>${p.price}</td><td>{monthlySalesLabel(p)}</td><td>{formatImportedAt(p.importedAt)}</td><td><span className={`risk risk-${p.returnRisk}`}>{p.returnRisk}</span></td><td><span className={pending?"data-status-badge":"data-status-ok"}>{pending?"数据待补":"数据完整"}</span></td>{showScore&&<td>{"placement" in p?<b className={`grade grade-${gradeOf(p)}`}>{gradeConclusion(p)}</b>:"—"}</td>}<td><button className="link" onClick={()=>edit(p)}>编辑</button>{!showScore&&<button className="danger" onClick={()=>remove(p.asin)}>删除</button>}</td></tr>})}</tbody></table>{!data.length&&<div className="empty table-empty"><b>暂无记录</b></div>}</div>}
function CompareDrawer({products,close}:{products:ScoredProduct[];close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="compare-modal"><div className="compare-head"><div><span className="eyebrow">PRODUCT COMPARISON</span><h2>产品并排对比</h2><p>一次最多展示前 4 个已选产品。</p></div><button onClick={close}>关闭</button></div>{products.length?<div className="compare-grid"><div className="compare-labels"><b>产品</b><span>推荐结论</span><span>售价 / 月销区间</span><span>增长 / 评论</span><span>利润率</span><span>包装毛重</span><span>数据状态</span></div>{products.map(p=>{const grade=gradeOf(p),warning=p.placement.needsData?(dataWarning(p)||"关键筛选数据待补"):"";return <div className="compare-column" key={p.asin}><div><ProductVisual product={p}/><h3><ProductTitle product={p}/></h3><small>{p.asin}</small></div><strong className={`grade grade-${grade}`}>{grade}<small>{gradeLabels[grade]}</small></strong><span>${p.price} / {monthlySalesLabel(p)}</span><span>{percent(p.salesGrowth)} / {compact(p.reviews)}</span><span>{percent(p.score.company.estimatedMargin)}</span><span>{withUnit(p.packageGrossKg,"kg")}</span><span className={warning?"data-status-badge":"data-status-ok"}>{warning||"数据完整"}</span></div>})}</div>:<div className="empty"><b>请先选择产品</b><span>在商品卡或表格中勾选 2—4 个产品后再对比。</span></div>}</section></div>}
function Form({product,set,save,cancel}:{product:Product;set:(p:Product)=>void;save:()=>void;cancel:()=>void}){const numeric=["price","monthlySales","launchDays","salesGrowth","estimatedMargin","packageGrossKg","priceUplift","rating","reviews","bsr","weight","complexity","differentiation"];return <div className="form">{fields.map(f=><label key={f} className={["title","titleZh","imageUrl","sellingPoints","painPoints","note","sourceUrl","packageDimensionsCm"].includes(f)?"wide":""}>{labels[f]}{["sellingPoints","painPoints","note"].includes(f)?<textarea value={String(product[f]??"")} onChange={e=>set({...product,[f]:e.target.value})}/>:f==="returnRisk"?<select value={product.returnRisk} onChange={e=>set({...product,returnRisk:e.target.value as Risk})}>{["低","中","高"].map(x=><option key={x}>{x}</option>)}</select>:<input type={numeric.includes(f)?"number":"text"} value={String(product[f]??"")} placeholder={f==="titleZh"?furnitureTitleZh(product.title):undefined} onChange={e=>set({...product,[f]:numeric.includes(f)?Number(e.target.value):e.target.value})}/>}</label>)}<div className="form-actions"><button onClick={cancel}>取消</button><button className="primary" onClick={save}>保存记录</button></div></div>}
function Settings({products,setProducts,favorites,setFavorites,notice}:{products:Product[];setProducts:(p:Product[])=>void;favorites:Set<string>;setFavorites:(p:Set<string>)=>void;notice:(s:string)=>void}){const rules=[["新品标准","上架不超过 180 天"],["早期验证","月销 50–300"],["爆款阶段","月销超过 300"],["评论壁垒","单 Listing 评论少于 100"],["目标价格","最低售价 100 美元"],["利润中线","20%，按可信度渐进加减分"],["包装数据","仅用于利润估算与数据完整性"]];const restore=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.products))throw Error();setProducts(d.products);setFavorites(new Set(d.favorites??[]));if(d.calibration)localStorage.setItem("linx-calibration-v1",JSON.stringify(d.calibration));if(d.batchCalibration)localStorage.setItem("linx-batch-calibration-v1",JSON.stringify(d.batchCalibration));notice("备份已恢复。")}catch{notice("备份文件无效。")}e.target.value=""};const backup=()=>{let calibration=null,batchCalibration=null;try{calibration=JSON.parse(localStorage.getItem("linx-calibration-v1")||"null");batchCalibration=JSON.parse(localStorage.getItem("linx-batch-calibration-v1")||"null")}catch{}saveFile("家具选品备份.json",JSON.stringify({products,favorites:[...favorites],calibration,batchCalibration},null,2),"application/json")};return <section className="panel settings"><div><span className="eyebrow">RECOMMENDATION RULES</span><h2>统一推荐规则</h2><p>A / B / C / D 表达开发兴趣，数据待补单独表达信息可信度；缺数据不会再自动变成 C。</p></div><div className="grade-guide"><span className="grade grade-A">A<small>重点考虑开发</small></span><span className="grade grade-B">B<small>一般产品</small></span><span className="grade grade-C">C<small>不感兴趣</small></span><span className="grade grade-D">D<small>垃圾箱</small></span></div><div className="weight-grid">{rules.map(([name,detail])=><div className="weight" key={name}><span>{name}<small>{detail}</small></span></div>)}</div><hr/><div className="backup"><div><h3>本地数据备份</h3><p>产品数据、收藏夹和两阶段校准反馈会一起备份。更换电脑前请下载。</p></div><div className="actions"><button onClick={backup}>下载 JSON 备份</button><label className="file">恢复备份<input type="file" accept=".json" onChange={restore}/></label></div></div></section>}
