"use client";
/* eslint-disable @next/next/no-img-element -- imported product images use arbitrary marketplace hosts */

import { ChangeEvent, useEffect, useMemo, useRef, useState } from "react";
import { attachSheetImageUrls, imageFromRow } from "./import-images";
import { Grade, dataWarningFor, gradeLabels, gradeOrder } from "./recommendation-grade";
import { potentialReasons } from "./product-potential";
import { OpportunityTrack } from "./opportunity-track";
import { diversifyOpportunityRows, opportunityFamilyCount } from "./opportunity-diversity";
import { auditProductPlacements, classifyFormalProduct, type PlacementAudit, type ProductPlacement, type ProductOrigin } from "./product-placement";
import { chineseTitleFromRow, furnitureTitleZh } from "./title-translation";
import { fullTitleZh } from "./full-title-translations";
import PaginationControls, { usePagination } from "./pagination";
import GarbageBin from "./garbage-bin";
import BatchCalibrationPanel from "./batch-calibration-panel";
import { BatchCalibrationCandidate, normalizeBatchCalibrationState, type BatchCalibrationState } from "./batch-calibration";
import { appendLearningEvent, appendReflectionReport, emptyLearningState, learningEvidenceCount, mergeLearningStates, migrateLegacyCalibration, normalizeLearningState, recycleProduct, restoreRecycledProduct, setPreferenceRuleStatus, type LearningEvent, type LearningState } from "./learning-state";
import { majorCategories, majorCategoryFor, majorCategoryLabel, presentMajorCategories } from "./major-category";
import { ManualCategoryProvider, ManualMajorCategoryField } from "./manual-major-category";
import { collapseProductVariants, productIdentityAsins } from "./product-variants";
import ProductDecisionActions from "./product-decision-actions";
import RecycleBin from "./recycle-bin";
import { buildLearnedGradeMap } from "./preference-learning";
import LearningReviewPanel from "./learning-review-panel";
import { buildReflectionReport, unreportedLearningEvents } from "./learning-review";

type Risk = "低" | "中" | "高";
type OpportunityView = "all" | Exclude<OpportunityTrack, "unmatched">;
type Product = { asin:string; parentAsin?:string; variantAsins?:string[]; variantCount?:number; brand?:string; title:string; titleZh?:string; category:string; manualMajorCategoryId?:string; price:number; rating:number; reviews:number; bsr:number; dimensions:string; weight:number; material:string; variants:string; sellingPoints:string; painPoints:string; sourceUrl:string; imageUrl?:string; importedAt?:string; note:string; complexity:number; differentiation:number; returnRisk:Risk; monthlySales?:number; monthlySalesEstimate?:{min:number;max:number;confidence?:string;source?:string}; launchDays?:number; salesGrowth?:number; packageGrossKg?:number; packageDimensionsCm?:string; estimatedMargin?:number; priceUplift?:number };
declare global { interface Window { __LINX_DATA__?: { products:Product[]; trash:Product[] } } }
const fields: (keyof Product)[] = ["asin","title","titleZh","imageUrl","importedAt","category","price","monthlySales","launchDays","salesGrowth","estimatedMargin","packageGrossKg","packageDimensionsCm","priceUplift","rating","reviews","bsr","dimensions","weight","material","variants","sellingPoints","painPoints","sourceUrl","note","complexity","differentiation","returnRisk"];
const labels: Record<keyof Product,string> = { asin:"ASIN",title:"英文标题",titleZh:"中文标题",imageUrl:"商品主图链接",importedAt:"导入时间",category:"类目",price:"价格(USD)",monthlySales:"月销量",launchDays:"上架天数",salesGrowth:"销量环比增长率",estimatedMargin:"已报价利润率(可选覆盖)",packageGrossKg:"单箱包装毛重(kg)",packageDimensionsCm:"包装尺寸(cm)",priceUplift:"改款提价潜力(可选覆盖)",rating:"评分",reviews:"评论数",bsr:"BSR",dimensions:"尺寸",weight:"重量(lb)",material:"材质",variants:"颜色/变体",sellingPoints:"卖点",painPoints:"差评痛点",sourceUrl:"来源链接",note:"中文备注",complexity:"结构复杂度(1-5)",differentiation:"差异化空间(1-5)",returnRisk:"退货风险" };
async function builtInProducts(){if(window.__LINX_DATA__)return window.__LINX_DATA__;const[productsResponse,trashResponse]=await Promise.all([fetch("/real-products.json"),fetch("/rejected-products.json")]);if(!productsResponse.ok||!trashResponse.ok)throw Error("built-in product data unavailable");return{products:await productsResponse.json() as Product[],trash:await trashResponse.json() as Product[]}}
function compute(p:Product,placement:ProductPlacement){
 const company={...placement.assessment,categoryVerdict:placement.opportunityTrackLabel?`${placement.opportunityTrackLabel} · ${placement.reasons.at(-1)??"已完成统一归位"}`:"垃圾箱 · 已触发硬性淘汰"};
 const dev=company.companyFit;
 const diff=Math.round((company.hiddenOpportunity*.7)+(Math.min(5,Math.max(1,p.differentiation))*20*.3));
 const market=company.demand;
 const risk=company.hardRejected?0:100;
 const total=placement.score;
 return{dev,diff,market,risk,total,reasons:company.reasons,company};
}
type ScoredProduct = Product&{score:ReturnType<typeof compute>;placement:ProductPlacement};
const navigationGroups = [
 {label:"选品决策",items:[["机会筛选","开发机会"],["潜力款","潜力新品"],["方向不匹配","暂不匹配"],["收藏夹","我的收藏"]]},
 {label:"持续学习",items:[["校准模式","偏好校准"],["学习复盘","学习复盘"],["数据待补","待补数据"],["推荐规则","分类标准与数据"]]},
 {label:"产品管理",items:[["数据管理","产品库"],["垃圾箱","D类淘汰库"],["回收站","30天回收站"]]},
] as const;
const compact=(value:number)=>value>0?new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:1}).format(value):"—";
const monthlySalesValue=(product:Product)=>Number(product.monthlySales??0)>0?Number(product.monthlySales):(product.monthlySalesEstimate?(product.monthlySalesEstimate.min+product.monthlySalesEstimate.max)/2:0);
const monthlySalesLabel=(product:Product)=>Number(product.monthlySales??0)>0?compact(Number(product.monthlySales)):product.monthlySalesEstimate?`${compact(product.monthlySalesEstimate.min)}–${compact(product.monthlySalesEstimate.max)}`:"—";
const withUnit=(value:number|undefined,unit:string)=>Number(value)>0?`${value} ${unit}`:"—";
const percent=(value:number|undefined)=>{const number=Number(value||0);return`${(Math.abs(number)<=2?number*100:number).toFixed(1)}%`};
const dataContext=(product:Product)=>({category:product.category,material:product.material,price:product.price});
const dataWarning=(product:Product)=>dataWarningFor(product.packageDimensionsCm,product.packageGrossKg,dataContext(product));
const gradeOf=(product:ScoredProduct):Grade=>product.placement.grade;
const interestOrder={priority:0,unrated:1,normal:1,low:2} as const;
const recommendationOrder=(a:ScoredProduct,b:ScoredProduct)=>interestOrder[a.score.company.interestTier]-interestOrder[b.score.company.interestTier]||gradeOrder[gradeOf(a)]-gradeOrder[gradeOf(b)]||b.score.total-a.score.total;
const formatImportedAt=(value:string|undefined)=>value?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"}).format(new Date(value)):"历史数据";
function saveFile(name:string,content:string,type="text/plain;charset=utf-8"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function blank():Product{return{asin:"",title:"",titleZh:"",imageUrl:"",importedAt:new Date().toISOString(),category:"客厅 / 边几",price:0,rating:0,reviews:0,bsr:99999,dimensions:"",weight:0,material:"",variants:"",sellingPoints:"",painPoints:"",sourceUrl:"",note:"",complexity:3,differentiation:3,returnRisk:"中"}}
function num(v:unknown){const match=String(v??"").replace(/,/g,"").match(/-?\d+(?:\.\d+)?/);return Number(match?.[0])||0}
function margin(v:unknown){const value=num(v);return value>0&&value<=1?value*100:value}
function sellerProduct(r:Record<string,unknown>):Product { const text=(v:unknown)=>String(v??""); const packageKg=num(r["包装重量（单位换算）"]); const title=text(r["商品标题"]),asin=text(r.ASIN).toUpperCase(),parent=text(r["父ASIN"]).toUpperCase(); return {asin,parentAsin:/^[A-Z0-9]{10}$/.test(parent)?parent:asin,brand:text(r["品牌"]),title,titleZh:chineseTitleFromRow(r),imageUrl:imageFromRow(r),importedAt:new Date().toISOString(),category:text(r["小类目"]||r["类目路径"]),price:num(r["价格($)"]),monthlySales:num(r["月销量"]),launchDays:num(r["上架天数"]),salesGrowth:num(r["销量环比增长率"]),packageGrossKg:packageKg,packageDimensionsCm:text(r["包装尺寸（单位换算）"]),rating:num(r["评分"]),reviews:num(r["评分数"]),bsr:num(r["小类BSR"]),dimensions:text(r["商品尺寸（单位换算）"]),weight:packageKg*2.205,material:text(r["详细参数"]),variants:text(r.SKU),sellingPoints:text(r["标签"]),painPoints:"",sourceUrl:text(r["商品详情页链接"]),note:text(r["品牌"]),complexity:3,differentiation:3,returnRisk:packageKg>49?"高":packageKg>22?"中":"低",estimatedMargin:margin(r["毛利率"]),priceUplift:3}; }

export default function Home(){
 const [tab,setTab]=useState("机会筛选"),[products,setProducts]=useState<Product[]>([]),[trash,setTrash]=useState<Product[]>([]),[editing,setEditing]=useState<Product|null>(null),[notice,setNotice]=useState("");
 const [favorites,setFavorites]=useState<Set<string>>(new Set()),[selected,setSelected]=useState<Set<string>>(new Set()),[hydrated,setHydrated]=useState(false),[compareOpen,setCompareOpen]=useState(false),[opportunityTrack,setOpportunityTrack]=useState<OpportunityView>("all");
 const [learning,setLearning]=useState<LearningState>(emptyLearningState),[learningReady,setLearningReady]=useState(false),[saveStatus,setSaveStatus]=useState("正在读取学习档案");
 const baselineProducts=useRef(new Map<string,Product>()),baselineTrash=useRef(new Map<string,Product>());
 const cloudSaveTimer=useRef<number|undefined>(undefined);
 const learningSessionId=useRef("");
 const [filters,setFilters]=useState({search:"",category:"all",grade:"全部",minSales:0,sort:"grade"});
 useEffect(()=>{const id=window.setTimeout(()=>{if(new URLSearchParams(window.location.search).get("tab")==="calibration")setTab("校准模式")},0);return()=>window.clearTimeout(id)},[]);
 // Compatibility for the former D-list navigation target.
 // eslint-disable-next-line react-hooks/set-state-in-effect
 useEffect(()=>{if(tab==="不推荐")setTab("垃圾箱")},[tab]);
 // Built-in pools are static assets so large imports do not make the Sites compiler parse megabytes of JSON repeatedly.
 useEffect(()=>{let cancelled=false;const id=window.setTimeout(()=>{void(async()=>{try{
  localStorage.removeItem("furniture-radar-v2");localStorage.removeItem("furniture-radar-v3");
  const builtIn=await builtInProducts();if(cancelled)return;
  baselineProducts.current=new Map(builtIn.products.map(p=>[p.asin,p]));baselineTrash.current=new Map(builtIn.trash.map(p=>[p.asin,p]));
  const productMap=new Map(baselineProducts.current),trashMap=new Map(baselineTrash.current);
  let legacyFavorites:string[]=[];
  const raw=localStorage.getItem("furniture-radar-v6")||localStorage.getItem("furniture-radar-v5")||localStorage.getItem("furniture-radar-v4");
  if(raw)try{const d=JSON.parse(raw);if(Array.isArray(d.productOverrides)){d.productOverrides.forEach((p:Product)=>productMap.set(p.asin,p));d.trashOverrides?.forEach((p:Product)=>trashMap.set(p.asin,p));d.deletedProducts?.forEach((asin:string)=>productMap.delete(asin));d.deletedTrash?.forEach((asin:string)=>trashMap.delete(asin))}else{d.products?.forEach((p:Product)=>productMap.set(p.asin,p));d.trash?.forEach((p:Product)=>trashMap.set(p.asin,p))}legacyFavorites=d.favorites??[]}catch{}
  const withChineseTitle=(p:Product)=>({...p,titleZh:fullTitleZh(p.asin,p.titleZh,p.title,p.category)});
  setProducts([...productMap.values()].map(withChineseTitle));setTrash([...trashMap.values()].map(withChineseTitle));
  let localProfile:LearningState;
  try{localProfile=normalizeLearningState(JSON.parse(localStorage.getItem("linx-learning-profile-v1")||"null"))}catch{localProfile=emptyLearningState()}
  if(!localProfile.legacyCalibration)try{localProfile=migrateLegacyCalibration(localProfile,JSON.parse(localStorage.getItem("linx-calibration-v1")||"null"))}catch{}
  if(!localProfile.batchCalibration)try{localProfile={...localProfile,batchCalibration:JSON.parse(localStorage.getItem("linx-batch-calibration-v1")||"null")}}catch{}
  if(!localProfile.favorites.length&&legacyFavorites.length)localProfile={...localProfile,favorites:legacyFavorites};
  let profile=localProfile;
  try{const response=await fetch("/api/learning-state",{cache:"no-store"});if(response.ok){const payload=await response.json() as {state:unknown;revision?:number};const cloud=normalizeLearningState(payload.state);if(Number(payload.revision)>0&&(learningEvidenceCount(cloud)>0||learningEvidenceCount(localProfile)>0))profile=mergeLearningStates(localProfile,cloud);setSaveStatus("云端学习档案已连接")}else setSaveStatus("已保存到本机")}catch{setSaveStatus("已保存到本机")}
  if(cancelled)return;setLearning(profile);setFavorites(new Set(profile.favorites));setLearningReady(true);
 }catch{if(!cancelled)setNotice("内置产品数据加载失败，请刷新页面重试。")}finally{if(!cancelled)setHydrated(true)}})()},0);return()=>{cancelled=true;window.clearTimeout(id)}},[]);
 useEffect(()=>{if(!hydrated)return;const productMap=new Map(products.map(p=>[p.asin,p])),trashMap=new Map(trash.map(p=>[p.asin,p]));const productOverrides=products.filter(p=>JSON.stringify(baselineProducts.current.get(p.asin))!==JSON.stringify(p));const trashOverrides=trash.filter(p=>JSON.stringify(baselineTrash.current.get(p.asin))!==JSON.stringify(p));const deletedProducts=[...baselineProducts.current.keys()].filter(asin=>!productMap.has(asin));const deletedTrash=[...baselineTrash.current.keys()].filter(asin=>!trashMap.has(asin));try{localStorage.setItem("furniture-radar-v6",JSON.stringify({productOverrides,trashOverrides,deletedProducts,deletedTrash,favorites:[...favorites]}));localStorage.removeItem("furniture-radar-v5");localStorage.removeItem("furniture-radar-v4")}catch{window.setTimeout(()=>setNotice("本机存储空间不足，请下载 JSON 备份保存本次修改。"),0)}},[products,trash,favorites,hydrated]);
 useEffect(()=>{if(!learningReady)return;const next={...learning,favorites:[...favorites]};try{localStorage.setItem("linx-learning-profile-v1",JSON.stringify(next))}catch{window.setTimeout(()=>setNotice("本机学习档案保存失败，请下载 JSON 备份。"),0)}if(cloudSaveTimer.current)window.clearTimeout(cloudSaveTimer.current);cloudSaveTimer.current=window.setTimeout(()=>{setSaveStatus("正在保存学习档案");void fetch("/api/learning-state",{method:"PUT",headers:{"Content-Type":"application/json"},body:JSON.stringify({state:next})}).then(async response=>{if(!response.ok)throw Error();const saved=normalizeLearningState((await response.json()).state);setSaveStatus(`云端已保存 · ${new Date(saved.updatedAt).toLocaleTimeString("zh-CN",{hour:"2-digit",minute:"2-digit"})}`)}).catch(()=>setSaveStatus("云端暂不可用 · 本机已保存"))},700);return()=>{if(cloudSaveTimer.current)window.clearTimeout(cloudSaveTimer.current)}},[learning,favorites,learningReady]);
 const recycledAsins=useMemo(()=>new Set(Object.keys(learning.recycleBin)),[learning.recycleBin]);
 const purgedAsins=useMemo(()=>new Set(learning.purgedAsins),[learning.purgedAsins]);
 const trashAsins=useMemo(()=>new Set(trash.flatMap(product=>productIdentityAsins(product))),[trash]);
 const productUniverse=useMemo<Product[]>(()=>collapseProductVariants([...new Map([...products,...trash].map(product=>[product.asin,product])).values()]).filter(product=>productIdentityAsins(product).every(asin=>!recycledAsins.has(asin)&&!purgedAsins.has(asin))),[products,trash,recycledAsins,purgedAsins]);
 const learnedGrades=useMemo(()=>buildLearnedGradeMap(productUniverse,learning),[productUniverse,learning]);
 const scoredUniverse=useMemo<ScoredProduct[]>(()=>productUniverse.map(p=>{const origin:ProductOrigin=p.importedAt?"import":"historical",identityAsins=productIdentityAsins(p);const latestManual=identityAsins.map(asin=>learning.gradeOverrides[asin]).filter(Boolean).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt))[0];const latestCategory=identityAsins.map(asin=>learning.categoryOverrides[asin]).filter(Boolean).sort((a,b)=>Date.parse(b.updatedAt)-Date.parse(a.updatedAt))[0];const manualGrade=latestManual?.grade??(identityAsins.some(asin=>trashAsins.has(asin))?"D":undefined);const learned=learnedGrades.get(p.asin);const placement=classifyFormalProduct({...p,manualFavorite:identityAsins.some(asin=>favorites.has(asin)),manualGrade,learnedGrade:learned?.grade,learnedScoreAdjustment:learned?.adjustment,learnedGradeEvidence:learned?{family:learned.family,count:learned.evidenceCount,reasons:learned.reasons}:undefined},origin);return{...p,manualMajorCategoryId:latestCategory?.categoryId??undefined,placement,score:compute(p,placement)}}),[productUniverse,learning.gradeOverrides,learning.categoryOverrides,trashAsins,favorites,learnedGrades]);
 const scoredProducts=useMemo(()=>scoredUniverse.filter(product=>gradeOf(product)!=="D"),[scoredUniverse]);
 const scoredTrash=useMemo(()=>scoredUniverse.filter(product=>gradeOf(product)==="D"),[scoredUniverse]);
 const placementAudit=useMemo(()=>auditProductPlacements(scoredUniverse.map(p=>p.placement)),[scoredUniverse]);
 const calibrationProducts=useMemo<BatchCalibrationCandidate[]>(()=>scoredProducts.filter(p=>p.placement.destination!=="garbage").map(p=>({asin:p.asin,title:p.title,titleZh:fullTitleZh(p.asin,p.titleZh,p.title,p.category),category:p.category,grade:gradeOf(p),score:p.score.total,interestTier:p.score.company.interestTier,imageUrl:p.imageUrl,sourceUrl:productUrl(p),price:p.price,monthlySales:p.monthlySales??0,reasons:p.score.reasons})),[scoredProducts]);
 const batchCalibrationState=useMemo<BatchCalibrationState>(()=>normalizeBatchCalibrationState(learning.batchCalibration),[learning.batchCalibration]);
 const rows=useMemo(()=>scoredProducts.filter(p=>(filters.category==="all"||majorCategoryFor(p).id===filters.category)&&(filters.grade==="全部"||gradeOf(p)===filters.grade)&&monthlySalesValue(p)>=filters.minSales&&`${p.asin} ${p.parentAsin??""} ${(p.variantAsins??[]).join(" ")} ${p.title} ${fullTitleZh(p.asin,p.titleZh,p.title,p.category)}`.toLowerCase().includes(filters.search.toLowerCase())).sort((a,b)=>filters.sort==="sales"?monthlySalesValue(b)-monthlySalesValue(a):filters.sort==="growth"?(b.salesGrowth??0)-(a.salesGrowth??0):filters.sort==="margin"?b.score.company.estimatedMargin-a.score.company.estimatedMargin:recommendationOrder(a,b)),[scoredProducts,filters]);
 const gradeCounts=placementAudit.grades;
 const dataPendingRows=useMemo(()=>scoredProducts.filter(p=>p.placement.needsData&&p.placement.destination!=="garbage").sort((a,b)=>b.score.company.demand-a.score.company.demand),[scoredProducts]);
 const trackCounts=useMemo<Record<OpportunityTrack,number>>(()=>({"red-ocean-blue":placementAudit.destinations["red-ocean-blue"],"blue-ocean-red":placementAudit.destinations["blue-ocean-red"],unmatched:placementAudit.destinations.unmatched}),[placementAudit]);
 const opportunityMatchedRows=useMemo(()=>scoredProducts.filter(p=>p.placement.destination==="red-ocean-blue"||p.placement.destination==="blue-ocean-red"),[scoredProducts]);
 const opportunityBase=useMemo(()=>rows.filter(p=>{if(p.placement.destination==="garbage")return false;if(filters.grade!=="全部")return true;return(p.placement.destination==="red-ocean-blue"||p.placement.destination==="blue-ocean-red")&&(opportunityTrack==="all"||p.placement.destination===opportunityTrack)}).sort(recommendationOrder),[rows,filters.grade,opportunityTrack]);
 const opportunityRows=useMemo(()=>diversifyOpportunityRows(opportunityBase),[opportunityBase]);
 const familyCount=useMemo(()=>opportunityFamilyCount(opportunityBase),[opportunityBase]);
 const unmatchedRows=useMemo(()=>scoredProducts.filter(p=>p.placement.destination==="unmatched").sort(recommendationOrder),[scoredProducts]);
 const rejectedRows=useMemo(()=>[...scoredTrash].sort((a,b)=>b.score.company.demand-a.score.company.demand),[scoredTrash]);
 const garbageRows=useMemo(()=>rejectedRows.map(({score,placement,...product})=>{void score;return{...product,hardRejectReasons:placement.reasons}}),[rejectedRows]);
 const potentialRows=useMemo(()=>scoredProducts.filter(p=>p.placement.potential&&p.placement.destination!=="garbage").sort((a,b)=>potentialReasons(b).length-potentialReasons(a).length||b.score.total-a.score.total),[scoredProducts]);
 const favoriteRows=useMemo(()=>scoredProducts.filter(p=>p.placement.favorite&&p.placement.destination!=="garbage").sort(recommendationOrder),[scoredProducts]);
 const selectedRows=useMemo(()=>scoredProducts.filter(p=>selected.has(p.asin)),[scoredProducts,selected]);
 const selectedUniverseRows=useMemo(()=>scoredUniverse.filter(p=>selected.has(p.asin)),[scoredUniverse,selected]);
 const cats=useMemo(()=>presentMajorCategories(scoredProducts),[scoredProducts]);
 const exportXlsx=async(output:ScoredProduct[],name="家具选品候选ASIN")=>{const XLSX=await import("xlsx");const header=[...fields.map(f=>labels[f]),"推荐等级","推荐结论","主归位","数据状态","潜力款","预估利润率","利润可信度","风险与提示","已收藏"];const data=[header,...output.map(p=>[...fields.map(f=>p[f]),gradeOf(p),gradeLabels[gradeOf(p)],p.placement.opportunityTrackLabel??"垃圾箱",p.placement.needsData?"数据待补":"数据完整",p.placement.potential?"是":"否",p.score.company.estimatedMargin,p.score.company.marginConfidence,[dataWarning(p),...p.placement.reasons].filter(Boolean).join("；"),p.placement.favorite?"是":"否"])];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(data),"选品清单");XLSX.writeFile(book,`${name}.xlsx`)};
 const updateLearning=(updater:(state:LearningState)=>LearningState)=>setLearning(old=>({...updater(old),updatedAt:new Date().toISOString()}));
 const newLearningEvent=(event:Omit<LearningEvent,"id"|"createdAt"|"sessionId">):LearningEvent=>{if(!learningSessionId.current)learningSessionId.current=`session-${crypto.randomUUID?.()??Math.random().toString(36).slice(2)}`;const createdAt=new Date().toISOString();return{...event,id:`event-${crypto.randomUUID?.()??`${Date.now()}-${Math.random()}`}`,createdAt,sessionId:learningSessionId.current}};
 const toggleFavorite=(asin:string)=>{const product=productUniverse.find(item=>productIdentityAsins(item).includes(asin)),identityAsins=product?productIdentityAsins(product):[asin],canonical=product?.asin??asin,next=new Set(favorites),removing=identityAsins.some(id=>next.has(id));identityAsins.forEach(id=>next.delete(id));if(!removing)next.add(canonical);setFavorites(next);updateLearning(profile=>appendLearningEvent({...profile,favorites:[...next]},newLearningEvent({kind:"favorite",value:removing?"remove":"add",asin:canonical})))};
 const toggleSelected=(asin:string)=>setSelected(old=>{const next=new Set(old);if(next.has(asin))next.delete(asin);else next.add(asin);return next});
 const selectVisible=(data:Array<{asin:string}>,checked:boolean)=>setSelected(old=>{const next=new Set(old);data.forEach(p=>checked?next.add(p.asin):next.delete(p.asin));return next});
 const favoriteSelected=()=>{const added=[...selected].filter(asin=>!favorites.has(asin)),next=new Set([...favorites,...selected]);setFavorites(next);updateLearning(profile=>added.reduce((state,asin)=>appendLearningEvent(state,newLearningEvent({kind:"favorite",value:"add",asin})),{...profile,favorites:[...next]}));setNotice(`已收藏 ${added.length} 个新产品。`)};
 const setManualGrade=(product:{asin:string},grade:Grade)=>{updateLearning(profile=>{const updatedAt=new Date().toISOString();return appendLearningEvent({...profile,gradeOverrides:{...profile.gradeOverrides,[product.asin]:{grade,updatedAt}}},newLearningEvent({kind:"grade",value:grade,asin:product.asin,previousValue:profile.gradeOverrides[product.asin]?.grade}))});setNotice(grade==="D"?`${product.asin} 已设为 D 类并进入淘汰库。`:`${product.asin} 已调整为 ${grade} 类，这条反馈只会影响后续软排序。`)};
 const setManualMajorCategory=(asin:string,categoryId:string)=>{updateLearning(profile=>{const previousValue=profile.categoryOverrides[asin]?.categoryId??undefined;const categoryOverrides={...profile.categoryOverrides,[asin]:{categoryId:categoryId||null,updatedAt:new Date().toISOString()}};return appendLearningEvent({...profile,categoryOverrides},newLearningEvent({kind:"category",value:categoryId||"unclassified",asin,previousValue}))});const label=categoryId?majorCategories.find(category=>category.id===categoryId):undefined;setNotice(label?`${asin} 已人工归入“${label.zh} / ${label.en}”，Amazon 原始类目仍完整保留。`:`${asin} 已恢复为未分类，等待 Amazon 实际类目或再次人工归类。`)};
 const gradeSelected=(grade:Grade)=>{const targets=selectedUniverseRows;if(!targets.length)return;updateLearning(profile=>{const updatedAt=new Date().toISOString();return targets.reduce((state,product)=>appendLearningEvent({...state,gradeOverrides:{...state.gradeOverrides,[product.asin]:{grade,updatedAt}}},newLearningEvent({kind:"grade",value:grade,asin:product.asin,previousValue:state.gradeOverrides[product.asin]?.grade})),profile)});setSelected(new Set());setNotice(`已将 ${targets.length} 款产品批量调整为 ${grade} 类${grade==="D"?"，并进入可复核淘汰库":""}。`)};
 const resolveProduct=(product:{asin:string})=>productUniverse.find(item=>productIdentityAsins(item).includes(product.asin));
 const plainProduct=(product:Product|ScoredProduct):Product=>{const scored=product as Partial<ScoredProduct>;if(!scored.score&&!scored.placement)return product as Product;const {score,placement,...plain}=product as ScoredProduct;void score;void placement;return plain};
 const moveToRecycle=(product:Product)=>{if(!window.confirm(`确认 ${product.asin} 是结合实际情况后绝不可能开发的产品吗？进入回收站30天后将自动清除详情。`))return;const current=scoredUniverse.find(item=>item.asin===product.asin);updateLearning(profile=>appendLearningEvent(recycleProduct(profile,plainProduct(product),current?gradeOf(current):"C"),newLearningEvent({kind:"recycle",value:"recycle",asin:product.asin})));setSelected(old=>{const next=new Set(old);next.delete(product.asin);return next});setNotice(`${product.asin} 已进入30天回收站。`)};
 const recycleSelected=()=>{const targets=selectedUniverseRows;if(!targets.length||!window.confirm(`确认已选 ${targets.length} 款都是结合实际情况后绝不可能开发的产品吗？进入回收站30天后将自动清除详情。`))return;updateLearning(profile=>targets.reduce((state,product)=>appendLearningEvent(recycleProduct(state,plainProduct(product),gradeOf(product)),newLearningEvent({kind:"recycle",value:"recycle",asin:product.asin})),profile));setSelected(new Set());setNotice(`${targets.length} 款产品已进入30天回收站。`)};
 const restoreFromRecycle=(asin:string,grade:Grade)=>{updateLearning(profile=>appendLearningEvent(restoreRecycledProduct(profile,asin,grade),newLearningEvent({kind:"restore",value:grade,asin})));setNotice(`${asin} 已从回收站恢复为 ${grade} 类。`)};
 const recordCalibrationEvent=(event:Omit<LearningEvent,"id"|"createdAt"|"sessionId">)=>updateLearning(profile=>appendLearningEvent(profile,newLearningEvent(event)));
 const saveReflection=()=>{const report=buildReflectionReport(productUniverse,learning,new Date().toISOString(),`reflection-${crypto.randomUUID?.()??Date.now()}`);if(!report){setNotice("本次没有新的校准操作，不会生成空复盘。");return}updateLearning(profile=>appendReflectionReport(profile,report));learningSessionId.current="";setTab("学习复盘");setNotice(`已生成复盘：记录 ${report.eventIds.length} 条操作，覆盖 ${report.familySignals.length} 个产品家族。`)} ;
 const changeRuleStatus=(family:string,status:"active"|"paused")=>{updateLearning(profile=>setPreferenceRuleStatus(profile,family,status));setNotice(`“${family}”软偏好已${status==="paused"?"暂停":"恢复"}，不会改变现有 ABCD。`)};
 const downloadTemplate=async()=>{const XLSX=await import("xlsx");const b=XLSX.utils.book_new();const sample=products[0]??blank();XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([fields.map(f=>labels[f]),fields.map(f=>sample[f])]),"竞品数据");XLSX.writeFile(b,"家具选品导入模板.xlsx")};
 const importProducts=async(e:ChangeEvent<HTMLInputElement>)=>{
  const file=e.target.files?.[0];
  if(!file)return;
  try{
   const XLSX=await import("xlsx");
   const wb=XLSX.read(await file.arrayBuffer());
   const sheet=wb.Sheets[wb.SheetNames[0]];
   const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});
   attachSheetImageUrls(sheet,raw,XLSX);
   const isSellerSprite=Object.prototype.hasOwnProperty.call(raw[0]??{},"商品标题");
   const importedAt=new Date().toISOString();
   const parsed=(isSellerSprite?raw.map(sellerProduct):raw.map(r=>Object.fromEntries(fields.map(f=>[f,f==="imageUrl"?imageFromRow(r):r[labels[f]]??r[f]??""])) as unknown as Product))
    .filter(p=>p.asin&&p.title)
    .map(p=>({...p,titleZh:fullTitleZh(p.asin,p.titleZh,p.title,p.category),importedAt,price:Number(p.price)||0,rating:Number(p.rating)||0,reviews:Number(p.reviews)||0,bsr:Number(p.bsr)||99999,weight:Number(p.weight)||0,monthlySales:Number(p.monthlySales)||0,launchDays:Number(p.launchDays)||9999,salesGrowth:Number(p.salesGrowth)||0,packageGrossKg:Number(p.packageGrossKg)||0,estimatedMargin:margin(p.estimatedMargin),priceUplift:Number(p.priceUplift)||3,complexity:Number(p.complexity)||3,differentiation:Number(p.differentiation)||3,returnRisk:["低","中","高"].includes(String(p.returnRisk))?p.returnRisk:"中" as Risk}));
   const incoming=collapseProductVariants([...new Map(parsed.map(p=>[p.asin,p] as const)).values()]);
   if(!incoming.length)throw Error();
   const missingImageAsins=incoming.filter(p=>!String(p.imageUrl??"").trim()).map(p=>p.asin);
   if(missingImageAsins.length){setNotice(`导入已暂停：${missingImageAsins.length} 款缺少主图（${missingImageAsins.slice(0,5).join("、")}${missingImageAsins.length>5?"…":""}）。请补图后重新导入。`);return}
   const before=products.length;
   const existingAsins=new Set(products.map(p=>p.asin));
   const netNew=incoming.filter(p=>!existingAsins.has(p.asin)).length;
   const duplicates=incoming.length-netNew;
   setProducts(old=>{const map=new Map(old.map(p=>[p.asin,p]));incoming.forEach(p=>map.set(p.asin,p));return[...map.values()]});
   setNotice(`已按 ASIN 累计导入 ${incoming.length} 条：正式池 ${before} → ${before+netNew}，净新增 ${netNew}，重复/更新 ${duplicates}；主图 ${incoming.length} 张、中文标题 ${incoming.length} 条，导入时间 ${formatImportedAt(importedAt)}。`)
  }catch{setNotice("导入失败：请使用模板列名，并确认 ASIN、英文标题和主图链接已填写。")}finally{e.target.value=""}
 };
 const save=()=>{if(!editing?.asin||!editing.title)return setNotice("请至少填写 ASIN 和英文标题。");if(!String(editing.imageUrl??"").trim())return setNotice("保存已暂停：正式产品必须有商品主图链接。");const normalized={...editing,titleZh:fullTitleZh(editing.asin,editing.titleZh,editing.title,editing.category)};setProducts(old=>{const i=old.findIndex(p=>p.asin===normalized.asin);return i<0?[normalized,...old]:old.map((p,n)=>n===i?normalized:p)});setTrash(old=>old.filter(p=>p.asin!==normalized.asin));setEditing(null);setNotice("记录已保存，主图与中文标题已确认，并已按统一条件重新归位。")} ;
 return <ManualCategoryProvider onAssign={setManualMajorCategory}><main><header className="app-header"><div><span className="eyebrow">AMAZON US · FURNITURE DEVELOPMENT</span><h1 className="brand">LIN<span>X</span><small>家具产品开发工作台</small></h1><p>每一次人工定级、收藏和偏好判断都会形成长期学习档案，持续修正后续产品分类。</p></div><div className="header-score"><span>当前开发机会</span><b>{opportunityMatchedRows.length}</b><small>{familyCount} 个产品家族 · {saveStatus}</small></div></header>
 <WorkspaceNav tab={tab} setTab={setTab} counts={{"机会筛选":opportunityMatchedRows.length,"方向不匹配":unmatchedRows.length,"校准模式":"可保存","学习复盘":unreportedLearningEvents(learning).length,"潜力款":potentialRows.length,"数据待补":dataPendingRows.length,"垃圾箱":garbageRows.length,"回收站":Object.keys(learning.recycleBin).length,"数据管理":scoredProducts.length,"收藏夹":placementAudit.labels.favorite}}/>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
 {tab==="机会筛选"&&<><section className="hero opportunity-hero"><div><span className="tag">LEARNING-DRIVEN PIPELINE</span><h2>开发机会总览</h2><p>模型先给建议，你的 A/B/C/D 调整拥有最终优先权，并会保存为以后分类的学习证据。</p><div className="pool-summary"><span><b>{scoredProducts.length}</b><small>在审产品</small></span><span><b>{opportunityMatchedRows.length}</b><small>进入机会池</small></span><span><b>{potentialRows.length}</b><small>潜力新品</small></span><span><b>{dataPendingRows.length}</b><small>待补关键数据</small></span></div><small>当前结果 {opportunityRows.length} 款 · 覆盖 {familyCount} 个产品家族</small></div><div className="grade-summary">{(["A","B","C","D"] as Grade[]).map(grade=><button key={grade} onClick={()=>grade==="D"?setTab("垃圾箱"):setFilters({...filters,grade})}><b className={`grade grade-${grade}`}>{grade}</b><span>{gradeLabels[grade]} · {gradeCounts[grade]} 款</span></button>)}</div></section><PlacementSummary audit={placementAudit}/><OpportunityTracks active={opportunityTrack} setActive={setOpportunityTrack} counts={trackCounts}/><section className="filters"><input placeholder="搜索 ASIN、英文或中文标题" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}><option value="all">全部大类目 / All Categories</option>{cats.map(category=><option key={category.id} value={category.id}>{category.zh} / {category.en}（{category.count}）</option>)}</select><select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value})}>{["全部","A","B","C"].map(x=><option key={x}>{x==="全部"?"全部推荐等级":`${x} · ${gradeLabels[x as Grade]}`}</option>)}</select><label>最低月销 <input type="number" value={filters.minSales||""} placeholder="不限" onChange={e=>setFilters({...filters,minSales:Number(e.target.value)||0})}/></label><select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="grade">开发优先顺序</option><option value="sales">月销量排序</option><option value="growth">增长率排序</option><option value="margin">利润率排序</option></select><button className="quiet" onClick={()=>setFilters({search:"",category:"all",grade:"全部",minSales:0,sort:"grade"})}>重置</button></section><BulkBar data={opportunityRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} gradeSelected={gradeSelected} recycleSelected={recycleSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Cards rows={opportunityRows} paginationKey={`${filters.search}|${filters.category}|${filters.grade}|${filters.minSales}|${filters.sort}|${opportunityTrack}`} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite} onGrade={setManualGrade} onRecycle={moveToRecycle}/></>}
 {tab==="方向不匹配"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">STRATEGY HOLD</span><h2>暂不匹配</h2><p>未触发硬性淘汰，但暂时缺少公司擅长的结构、材质或场景机会。你可以直接重新定级或放入回收站。</p></div><span className="tag">{unmatchedRows.length} 款待复核</span></div><BulkBar data={unmatchedRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} gradeSelected={gradeSelected} recycleSelected={recycleSelected} exportSelected={()=>exportXlsx(selectedRows,"暂不匹配已选")} compare={()=>setCompareOpen(true)}/><Cards rows={unmatchedRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite} onGrade={setManualGrade} onRecycle={moveToRecycle}/></section>}
  {tab==="校准模式"&&<BatchCalibrationPanel products={calibrationProducts} value={batchCalibrationState} onChange={(state)=>updateLearning(profile=>({...profile,batchCalibration:state}))} onLearningEvent={recordCalibrationEvent} onSave={saveReflection} onGrade={setManualGrade} onRecycle={(product)=>{const resolved=resolveProduct(product);if(resolved)moveToRecycle(resolved)}}/>}
 {tab==="学习复盘"&&<LearningReviewPanel products={productUniverse} learning={learning} onGenerate={saveReflection} onRuleStatus={changeRuleStatus}/>}
 {tab==="潜力款"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">EARLY OPPORTUNITIES</span><h2>潜力新品</h2><p>聚焦上架不超过 180 天、月销 50–300、评论较少，并出现增长、造型或改款信号的早期机会。</p></div><span className="tag">{potentialRows.length} 款潜力新品</span></div><BulkBar data={potentialRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} gradeSelected={gradeSelected} recycleSelected={recycleSelected} exportSelected={()=>exportXlsx(selectedRows,"潜力款已选")} compare={()=>setCompareOpen(true)}/><Cards rows={potentialRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite} onGrade={setManualGrade} onRecycle={moveToRecycle}/></section>}
 {tab==="数据待补"&&<section className="panel data-pending-panel"><div className="section-title"><div><span className="eyebrow">DATA READINESS</span><h2>待补数据</h2><p>集中处理包装、材质、销量或上架时间等缺口。数据完整度与 A/B/C/D 开发兴趣保持独立。</p></div><span className="tag">{dataPendingRows.length} 款待补</span></div><BulkBar data={dataPendingRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} gradeSelected={gradeSelected} recycleSelected={recycleSelected} exportSelected={()=>exportXlsx(selectedRows,"数据待补产品")} compare={()=>setCompareOpen(true)}/><Cards rows={dataPendingRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite} onGrade={setManualGrade} onRecycle={moveToRecycle}/></section>}
 {tab==="数据管理"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">PRODUCT DATA</span><h2>产品库</h2><p>{scoredProducts.length} 个在审 ASIN；A/B/C 可直接调整，D 进入淘汰库，没有参考意义的产品进入30天回收站。</p></div><div className="actions"><span className="tag">按 ASIN 累计追加/更新</span><button onClick={downloadTemplate}>下载 XLSX 模板</button><label className="primary file">导入 CSV / XLSX<input type="file" accept=".csv,.xlsx,.xls" onChange={importProducts}/></label><button onClick={()=>setEditing(blank())}>+ 新增记录</button></div></div>{editing?<Form product={editing} set={setEditing} save={save} cancel={()=>setEditing(null)}/>:<><BulkBar data={scoredProducts} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} gradeSelected={gradeSelected} recycleSelected={recycleSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Table data={scoredProducts} edit={setEditing} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite} onGrade={setManualGrade} onRecycle={moveToRecycle}/></>}</section>}
 {tab==="垃圾箱"&&<GarbageBin products={garbageRows} selected={selected} favorites={favorites} toggleSelected={toggleSelected} selectVisible={selectVisible} onFavorite={toggleFavorite} onFavoriteSelected={favoriteSelected} onGradeSelected={gradeSelected} onRecycleSelected={recycleSelected} onGrade={setManualGrade} onRecycle={(product)=>moveToRecycle(product as Product)}/>}
 {tab==="回收站"&&<RecycleBin entries={Object.values(learning.recycleBin)} favorites={favorites} toggleFavorite={toggleFavorite} restore={restoreFromRecycle}/>}
 {tab==="收藏夹"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">MY DEVELOPMENT LIST</span><h2>我的收藏</h2><p>保留需要持续跟进的产品，可跨页多选、并排比较或导出评审。</p></div><button className="primary" disabled={!favoriteRows.length} onClick={()=>exportXlsx(favoriteRows,"收藏产品")}>导出收藏</button></div><BulkBar data={favoriteRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} gradeSelected={gradeSelected} recycleSelected={recycleSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Cards rows={favoriteRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite} onGrade={setManualGrade} onRecycle={moveToRecycle}/></section>}
 {tab==="推荐规则"&&<Settings products={products} setProducts={setProducts} favorites={favorites} setFavorites={setFavorites} learning={learning} setLearning={setLearning} notice={setNotice}/>}</main>
 {compareOpen&&<CompareDrawer products={selectedRows.slice(0,4)} close={()=>setCompareOpen(false)} onGrade={setManualGrade} onRecycle={moveToRecycle}/>}
 </ManualCategoryProvider>;
}
function WorkspaceNav({tab,setTab,counts}:{tab:string;setTab:(tab:string)=>void;counts:Record<string,number|string|undefined>}){return <nav className="workspace-nav" aria-label="LINX 工作区导航">{navigationGroups.map(group=><section className="nav-group" key={group.label}><span>{group.label}</span><div>{group.items.map(([id,label])=><button key={id} className={tab===id?"active":""} onClick={()=>setTab(id)}>{label}{counts[id]!==undefined&&counts[id]!==0?<em>{counts[id]}</em>:null}</button>)}</div></section>)}</nav>}
function BulkBar({data,selected,selectVisible,favoriteSelected,gradeSelected,recycleSelected,exportSelected,compare}:{data:Product[];selected:Set<string>;selectVisible:(data:Array<{asin:string}>,checked:boolean)=>void;favoriteSelected:()=>void;gradeSelected:(grade:Grade)=>void;recycleSelected:()=>void;exportSelected:()=>void;compare:()=>void}){const visibleSelected=data.filter(p=>selected.has(p.asin)).length;const allSelected=data.length>0&&visibleSelected===data.length;return <div className="bulk-bar"><label><input type="checkbox" checked={allSelected} onChange={e=>selectVisible(data,e.target.checked)}/><span>{allSelected?"取消全选":"选择全部筛选结果"}</span></label><span className="result-count">{data.length} 个结果</span>{selected.size>0&&<div className="bulk-actions"><b>已选 {selected.size}</b><button onClick={favoriteSelected}>♥ 批量收藏</button><span className="bulk-grade-label">批量定级</span>{(["A","B","C","D"] as Grade[]).map(grade=><button className={`bulk-grade bulk-grade-${grade}`} key={grade} onClick={()=>gradeSelected(grade)}>{grade}</button>)}<button className="danger-action" onClick={recycleSelected}>批量回收</button><button onClick={compare}>并排对比</button><button onClick={exportSelected}>导出已选</button></div>}</div>}
function ProductVisual({product}:{product:Product}){const[failed,setFailed]=useState(false);return <div className="product-visual"><span aria-hidden="true">▱</span>{product.imageUrl&&!failed&&<img src={product.imageUrl} alt={product.title} loading="lazy" onError={()=>setFailed(true)}/>}<small>{failed?"主图暂时无法加载":product.imageUrl?"":"导入主图后显示"}</small></div>}
function productUrl(product:Product){const source=product.sourceUrl?.trim();if(source)return source;return/^[A-Z0-9]{10}$/i.test(product.asin)?`https://www.amazon.com/dp/${product.asin}`:`https://www.amazon.com/s?k=${encodeURIComponent(product.title)}`}
function ProductTitle({product}:{product:Product}){return <><a href={productUrl(product)} target="_blank" rel="noreferrer" title="打开 Amazon Listing">{product.title}<span className="external">↗</span></a><span className="title-zh">{fullTitleZh(product.asin,product.titleZh,product.title,product.category)}</span><ManualMajorCategoryField product={product}/></>}
function OpportunityTracks({active,setActive,counts}:{active:OpportunityView;setActive:(track:OpportunityView)=>void;counts:Record<OpportunityTrack,number>}){const tracks:[OpportunityView,string,string,string,number][]=[["all","全部开发机会","跨家族总览","成熟类目与细分场景交错展示，优先发现可落地机会。",counts["red-ocean-blue"]+counts["blue-ocean-red"]],["red-ocean-blue","成熟类目创新","造型与结构升级","聚焦柜类、书架、电视柜和玄关家具的外观与结构差异化。",counts["red-ocean-blue"]],["blue-ocean-red","细分场景渗透","功能与使用场景","聚焦宠物、洗衣、沙龙、前台、手作和影音等专用家具。",counts["blue-ocean-red"]]];return <section className="track-switcher" aria-label="开发策略赛道">{tracks.map(([id,title,subtitle,description,count])=><button key={id} className={active===id?"active":""} onClick={()=>setActive(id)}><span>{subtitle}</span><b>{title}</b><p>{description}</p><em>{count} 款</em></button>)}</section>}
function PlacementSummary({audit}:{audit:PlacementAudit}){const destinations=[["成熟类目创新",audit.destinations["red-ocean-blue"]],["细分场景渗透",audit.destinations["blue-ocean-red"]],["暂不匹配",audit.destinations.unmatched],["硬性淘汰",audit.destinations.garbage]] as const;return <section className={`placement-summary ${audit.valid?"is-valid":"is-invalid"}`} aria-label="产品分类健康度"><div className="placement-status"><span className="eyebrow">CLASSIFICATION HEALTH</span><b>{audit.valid?"分类运行正常":"分类需要检查"}</b><small>{audit.traceable}/{audit.total} 款产品可追溯</small></div><div className="placement-counts">{destinations.map(([label,count])=><span key={label}><b>{count}</b><small>{label}</small></span>)}</div><div className="placement-labels"><span>潜力新品 <b>{audit.labels.potential}</b></span><span>待补数据 <b>{audit.labels.needsData}</b></span><span>已收藏 <b>{audit.labels.favorite}</b></span></div>{!audit.valid&&<p>{audit.errors.join("；")}</p>}</section>}
function Cards({rows,paginationKey="stable-product-list",edit,selected,favorites,toggleSelected,toggleFavorite,onGrade,onRecycle}:{rows:ScoredProduct[];paginationKey?:unknown;edit:(p:Product)=>void;selected:Set<string>;favorites:Set<string>;toggleSelected:(asin:string)=>void;toggleFavorite:(asin:string)=>void;onGrade:(p:Product,grade:Grade)=>void;onRecycle:(p:Product)=>void}){
 const pager=usePagination(rows,paginationKey),anchor=useRef<HTMLDivElement>(null);const goPage=(page:number)=>{pager.setPage(page);window.requestAnimationFrame(()=>anchor.current?.scrollIntoView({behavior:"smooth",block:"start"}))};
 const pageSelected=pager.pageItems.filter(p=>selected.has(p.asin)).length;
 const selectPage=(checked:boolean)=>pager.pageItems.forEach(p=>{if(selected.has(p.asin)!==checked)toggleSelected(p.asin)});
 const controls=()=> <PaginationControls page={pager.page} totalPages={pager.totalPages} start={pager.start} end={pager.end} total={rows.length} pageSize={pager.pageSize} pageSelection={{checked:pager.pageItems.length>0&&pageSelected===pager.pageItems.length,selectedCount:pageSelected,total:pager.pageItems.length,onChange:selectPage}} onPageChange={goPage} onPageSizeChange={pager.setPageSize}/>;
 return <div className="paged-products" ref={anchor}>{controls()}<section className="cards">{pager.pageItems.map(p=>{
  const potential=p.placement.potential,warning=p.placement.needsData?(dataWarning(p)||"关键筛选数据待补"):"",grade=gradeOf(p);
  return <article className={`card ${selected.has(p.asin)?"selected":""}`} key={p.asin} tabIndex={0}><div className="card-select"><label title="选择产品"><input type="checkbox" checked={selected.has(p.asin)} onChange={()=>toggleSelected(p.asin)}/></label><button className={`heart ${favorites.has(p.asin)?"active":""}`} onClick={()=>toggleFavorite(p.asin)} aria-label={favorites.has(p.asin)?"取消收藏":"收藏产品"}>♥</button></div><ProductVisual product={p}/><div className="card-body"><div className="card-top"><div className="card-labels">{warning&&<span className="data-status-badge">数据待补</span>}{potential&&<span className="potential-badge">潜力款</span>}</div><strong className={`grade grade-${grade}`}>{grade}<small>{gradeLabels[grade]}</small></strong></div><span className="category" title={p.category}>{majorCategoryLabel(p)}</span><h3><ProductTitle product={p}/></h3><p className="asin">父 ASIN: {p.parentAsin??p.asin}{Number(p.variantCount??1)>1?` · ${p.variantCount} 个变体`:""}</p><div className="quick-stats"><div className="price-stat"><b>{p.price>0?`$${p.price}`:"—"}</b><span>售价</span></div><div><b>{monthlySalesLabel(p)}</b><span>月销区间</span></div><div><b>★ {p.rating||"—"}</b><span>{compact(p.reviews)} 条评论</span></div><div><b>{p.bsr>0?`#${compact(p.bsr)}`:"—"}</b><span>类目 BSR</span></div></div><ProductDecisionActions grade={grade} onGrade={(value)=>onGrade(p,value)} onRecycle={()=>onRecycle(p)} compact/><div className="hover-hint">悬停查看更多信息 ↓</div><div className="card-details"><div className="detail-grid"><span><b className={(p.salesGrowth??0)>0?"up":""}>{(p.salesGrowth??0)>0?"+":""}{percent(p.salesGrowth)}</b>销量增长</span><span><b>{percent(p.score.company.estimatedMargin)}</b>预估利润</span><span><b>{withUnit(p.packageGrossKg,"kg")}</b>包装毛重</span><span><b>{withUnit(p.launchDays,"天")}</b>上架时间</span><span><b>{formatImportedAt(p.importedAt)}</b>导入时间</span></div><div className="meter"><i style={{width:p.score.dev+"%"}}/></div><p className="opportunity">{potential?`潜力信号：${potentialReasons(p).join("、")}`:p.score.company.affinity.length?`匹配方向：${p.score.company.affinity.join("、")}`:p.score.company.trendElements.length?`机会元素：${p.score.company.trendElements.join("、")}`:p.note||"待补充改款方向"}</p><p className={warning?"reason data-warning":"reason"}>{warning||(p.score.reasons.length?p.score.reasons.slice(0,2).join(" · "):"物流与开发风险可控")}</p></div><div className="card-bottom"><span>{p.score.company.categoryVerdict}</span><button onClick={()=>edit(p)}>完整数据 →</button></div></div></article>
 })}{!rows.length&&<div className="empty"><b>这里暂时没有产品</b><span>调整筛选条件，或在商品卡上点击红心加入收藏。</span></div>}</section>{controls()}</div>
}
function TableProductImage({product}:{product:Product}){const[failed,setFailed]=useState(false);return <span className="table-product-image">{product.imageUrl&&!failed?<img src={product.imageUrl} alt={`${product.title} 主图`} loading="lazy" onError={()=>setFailed(true)}/>:<small>{failed?"加载失败":"无主图"}</small>}</span>}
function Table({data,edit,selected,favorites,toggleSelected,toggleFavorite,onGrade,onRecycle}:{data:ScoredProduct[];edit:(p:Product)=>void;selected:Set<string>;favorites:Set<string>;toggleSelected:(asin:string)=>void;toggleFavorite:(asin:string)=>void;onGrade:(p:Product,grade:Grade)=>void;onRecycle:(p:Product)=>void}){
 const pager=usePagination(data,"product-library"),anchor=useRef<HTMLDivElement>(null);
 const goPage=(page:number)=>{pager.setPage(page);window.requestAnimationFrame(()=>anchor.current?.scrollIntoView({behavior:"smooth",block:"start"}))};
 const pageSelected=pager.pageItems.filter(p=>selected.has(p.asin)).length;
 const selectPage=(checked:boolean)=>pager.pageItems.forEach(p=>{if(selected.has(p.asin)!==checked)toggleSelected(p.asin)});
 const controls=()=> <PaginationControls page={pager.page} totalPages={pager.totalPages} start={pager.start} end={pager.end} total={data.length} pageSize={pager.pageSize} pageSelection={{checked:pager.pageItems.length>0&&pageSelected===pager.pageItems.length,selectedCount:pageSelected,total:pager.pageItems.length,onChange:selectPage}} onPageChange={goPage} onPageSizeChange={pager.setPageSize}/>;
 return <div className="paged-table" ref={anchor}>{controls()}<div className="table-wrap"><table><thead><tr><th className="check-col"></th><th>主图 / ASIN / 商品</th><th>类目</th><th>价格</th><th>月销区间</th><th>导入时间</th><th>风险</th><th>数据状态</th><th>操作</th></tr></thead><tbody>{pager.pageItems.map(p=>{const pending=p.placement.needsData;return <tr key={p.asin} className={selected.has(p.asin)?"selected-row":""}><td><input type="checkbox" checked={selected.has(p.asin)} onChange={()=>toggleSelected(p.asin)}/></td><td><div className="table-product"><TableProductImage product={p}/><button className={`heart ${favorites.has(p.asin)?"active":""}`} onClick={()=>toggleFavorite(p.asin)}>♥</button><div><b>{p.asin}</b><span><ProductTitle product={p}/></span></div></div></td><td>{p.category}</td><td>{p.price>0?`$${p.price}`:"—"}</td><td>{monthlySalesLabel(p)}</td><td>{formatImportedAt(p.importedAt)}</td><td><span className={`risk risk-${p.returnRisk}`}>{p.returnRisk}</span></td><td><span className={pending?"data-status-badge":"data-status-ok"}>{pending?"数据待补":"数据完整"}</span></td><td className="table-decisions"><button className="link" onClick={()=>edit(p)}>编辑</button><ProductDecisionActions grade={gradeOf(p)} onGrade={(grade)=>onGrade(p,grade)} onRecycle={()=>onRecycle(p)} compact/></td></tr>})}</tbody></table>{!data.length&&<div className="empty table-empty"><b>暂无记录</b></div>}</div>{controls()}</div>
}
function CompareDrawer({products,close,onGrade,onRecycle}:{products:ScoredProduct[];close:()=>void;onGrade:(p:Product,grade:Grade)=>void;onRecycle:(p:Product)=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="compare-modal"><div className="compare-head"><div><span className="eyebrow">PRODUCT COMPARISON</span><h2>产品并排对比</h2><p>一次最多展示前 4 个已选产品，可在对比中直接修正分类。</p></div><button onClick={close}>关闭</button></div>{products.length?<div className="compare-grid"><div className="compare-labels"><b>产品</b><span>推荐结论</span><span>人工分类</span><span>售价 / 月销区间</span><span>增长 / 评论</span><span>利润率</span><span>包装毛重</span><span>数据状态</span></div>{products.map(p=>{const grade=gradeOf(p),warning=p.placement.needsData?(dataWarning(p)||"关键筛选数据待补"):"";return <div className="compare-column" key={p.asin}><div><ProductVisual product={p}/><h3><ProductTitle product={p}/></h3><small>{p.asin}</small></div><strong className={`grade grade-${grade}`}>{grade}<small>{gradeLabels[grade]}</small></strong><ProductDecisionActions grade={grade} onGrade={(value)=>onGrade(p,value)} onRecycle={()=>onRecycle(p)} compact/><span>{p.price>0?`$${p.price}`:"—"} / {monthlySalesLabel(p)}</span><span>{percent(p.salesGrowth)} / {compact(p.reviews)}</span><span>{percent(p.score.company.estimatedMargin)}</span><span>{withUnit(p.packageGrossKg,"kg")}</span><span className={warning?"data-status-badge":"data-status-ok"}>{warning||"数据完整"}</span></div>})}</div>:<div className="empty"><b>请先选择产品</b><span>在商品卡或表格中勾选 2—4 个产品后再对比。</span></div>}</section></div>}
function Form({product,set,save,cancel}:{product:Product;set:(p:Product)=>void;save:()=>void;cancel:()=>void}){const numeric=["price","monthlySales","launchDays","salesGrowth","estimatedMargin","packageGrossKg","priceUplift","rating","reviews","bsr","weight","complexity","differentiation"];return <div className="form">{fields.map(f=><label key={f} className={["title","titleZh","imageUrl","sellingPoints","painPoints","note","sourceUrl","packageDimensionsCm"].includes(f)?"wide":""}>{labels[f]}{["sellingPoints","painPoints","note"].includes(f)?<textarea value={String(product[f]??"")} onChange={e=>set({...product,[f]:e.target.value})}/>:f==="returnRisk"?<select value={product.returnRisk} onChange={e=>set({...product,returnRisk:e.target.value as Risk})}>{["低","中","高"].map(x=><option key={x}>{x}</option>)}</select>:<input type={numeric.includes(f)?"number":"text"} value={String(product[f]??"")} placeholder={f==="titleZh"?furnitureTitleZh(product.title,product.category):undefined} onChange={e=>set({...product,[f]:numeric.includes(f)?Number(e.target.value):e.target.value})}/>}</label>)}<div className="form-actions"><button onClick={cancel}>取消</button><button className="primary" onClick={save}>保存记录</button></div></div>}
function Settings({products,setProducts,favorites,setFavorites,learning,setLearning,notice}:{products:Product[];setProducts:(p:Product[])=>void;favorites:Set<string>;setFavorites:(p:Set<string>)=>void;learning:LearningState;setLearning:(p:LearningState)=>void;notice:(s:string)=>void}){const rules=[["A 类","最高设计开发价值：可能是整款，也可能只是某个造型元素、结构或功能值得借鉴，不等于单纯喜欢整款产品"],["B 类","良好且健康的开发候选，应当是产品池中占比最多的主体"],["C 类","只有小概率会开发，仍保留少量参考价值和重新评估空间"],["D 类","系统筛选后判断不适合当前方向的产品，需要持续接受你的纠错，不代表永远不能做"],["回收站","你结合实际情况后确认绝不可能开发的产品；即使符合部分硬性要求也可以进入，30天后清除详情"],["待补数据","只表达信息缺口，不改变 A/B/C/D 开发概率"]];const restore=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.products))throw Error();const restored=normalizeLearningState(d.learning??{...emptyLearningState(),favorites:d.favorites??[],batchCalibration:d.batchCalibration??null});setProducts(d.products.map((p:Product)=>({...p,titleZh:fullTitleZh(p.asin,p.titleZh,p.title,p.category)})));setLearning(restored);setFavorites(new Set(restored.favorites));notice("备份已恢复：产品、人工分类、回收站、收藏和偏好反思已重新载入。")}catch{notice("备份文件无效。")}e.target.value=""};const backup=()=>saveFile("LINX-产品与学习档案.json",JSON.stringify({products,learning:{...learning,favorites:[...favorites]}},null,2),"application/json");return <section className="panel settings"><div><span className="eyebrow">CLASSIFICATION & LEARNING</span><h2>分类与持续学习</h2><p>系统初判负责提效，你的人工分类、收藏和校准结论拥有最终优先权，并同步保存为公司学习档案。</p></div><div className="grade-guide"><span className="grade grade-A">A<small>高价值设计机会</small></span><span className="grade grade-B">B<small>良好开发候选</small></span><span className="grade grade-C">C<small>低概率开发</small></span><span className="grade grade-D">D<small>不适合当前方向</small></span></div><div className="weight-grid">{rules.map(([name,detail])=><div className="weight" key={name}><span>{name}<small>{detail}</small></span></div>)}</div><hr/><div className="backup"><div><h3>产品与学习档案备份</h3><p>人工 ABCD、回收站、收藏和偏好反思会云端保存，也可以下载 JSON 留档或迁移。</p></div><div className="actions"><button onClick={backup}>下载 JSON 备份</button><label className="file">恢复备份<input type="file" accept=".json" onChange={restore}/></label></div></div></section>}
