"use client";
/* eslint-disable @next/next/no-img-element -- imported product images use arbitrary marketplace hosts */

import { ChangeEvent, useEffect, useMemo, useState } from "react";
import { assess } from "./opportunity";
import { attachSheetImageUrls, imageFromRow } from "./import-images";
import realProducts from "./real-products.json";
import { DataStatus, Grade, dataStatusFor, dataWarningFor, gradeLabels, gradeOrder, gradeWithDataStatus } from "./recommendation-grade";
import { isPotentialProduct, potentialReasons } from "./product-potential";
import { classifyOpportunityTrack, OpportunityTrack, trackLabels } from "./opportunity-track";
import { chineseTitleFromRow, furnitureTitleZh } from "./title-translation";
import { fullTitleZh } from "./full-title-translations";
import BatchCalibrationPanel from "./batch-calibration-panel";
import { BatchCalibrationCandidate } from "./batch-calibration";

type Risk = "低" | "中" | "高";
type Product = { asin:string; title:string; titleZh?:string; category:string; price:number; rating:number; reviews:number; bsr:number; dimensions:string; weight:number; material:string; variants:string; sellingPoints:string; painPoints:string; sourceUrl:string; imageUrl?:string; importedAt?:string; note:string; complexity:number; differentiation:number; returnRisk:Risk; monthlySales?:number; launchDays?:number; salesGrowth?:number; packageGrossKg?:number; packageDimensionsCm?:string; estimatedMargin?:number; priceUplift?:number };
const fields: (keyof Product)[] = ["asin","title","titleZh","imageUrl","importedAt","category","price","monthlySales","launchDays","salesGrowth","estimatedMargin","packageGrossKg","packageDimensionsCm","priceUplift","rating","reviews","bsr","dimensions","weight","material","variants","sellingPoints","painPoints","sourceUrl","note","complexity","differentiation","returnRisk"];
const labels: Record<keyof Product,string> = { asin:"ASIN",title:"英文标题",titleZh:"中文标题",imageUrl:"商品主图链接",importedAt:"导入时间",category:"类目",price:"价格(USD)",monthlySales:"月销量",launchDays:"上架天数",salesGrowth:"销量环比增长率",estimatedMargin:"已报价利润率(可选覆盖)",packageGrossKg:"单箱包装毛重(kg)",packageDimensionsCm:"包装尺寸(cm)",priceUplift:"改款提价潜力(可选覆盖)",rating:"评分",reviews:"评论数",bsr:"BSR",dimensions:"尺寸",weight:"重量(lb)",material:"材质",variants:"颜色/变体",sellingPoints:"卖点",painPoints:"差评痛点",sourceUrl:"来源链接",note:"中文备注",complexity:"结构复杂度(1-5)",differentiation:"差异化空间(1-5)",returnRisk:"退货风险" };
const samples:Product[]=realProducts as Product[];
function compute(p:Product){
 const company=assess({asin:p.asin,title:p.title,category:p.category,price:p.price,monthlySales:p.monthlySales??0,launchDays:p.launchDays??9999,salesGrowth:p.salesGrowth??0,rating:p.rating,reviews:p.reviews,packageGrossKg:p.packageGrossKg??p.weight/2.205,packageDimensionsCm:p.packageDimensionsCm??p.dimensions,material:p.material,estimatedMargin:p.estimatedMargin??0,priceUplift:p.priceUplift??0,sourceUrl:p.sourceUrl});
 const track=classifyOpportunityTrack(p,company);
 company.categoryVerdict=`${trackLabels[track.track]} · ${track.reasons[0]}`;
 const dev=company.companyFit;
 const diff=Math.round((company.hiddenOpportunity*.7)+(Math.min(5,Math.max(1,p.differentiation))*20*.3));
 const market=company.demand;
 const risk=company.hardRejected?0:100;
 const total=company.score;
 return{dev,diff,market,risk,total,reasons:company.reasons,company};
}
type ScoredProduct = Product&{score:ReturnType<typeof compute>};
const compact=(value:number)=>value>0?new Intl.NumberFormat("zh-CN",{notation:"compact",maximumFractionDigits:1}).format(value):"—";
const withUnit=(value:number|undefined,unit:string)=>Number(value)>0?`${value} ${unit}`:"—";
const percent=(value:number|undefined)=>{const number=Number(value||0);return`${(Math.abs(number)<=2?number*100:number).toFixed(1)}%`};
const dataContext=(product:Product)=>({category:product.category,material:product.material,price:product.price});
const dataStatus=(product:Product):DataStatus=>dataStatusFor(product.packageDimensionsCm,product.packageGrossKg,dataContext(product));
const dataWarning=(product:Product)=>dataWarningFor(product.packageDimensionsCm,product.packageGrossKg,dataContext(product));
const gradeOf=(product:ScoredProduct):Grade=>gradeWithDataStatus(product.score.company.decision,dataStatus(product));
const interestOrder={priority:0,unrated:1,normal:1,low:2} as const;
const recommendationOrder=(a:ScoredProduct,b:ScoredProduct)=>interestOrder[a.score.company.interestTier]-interestOrder[b.score.company.interestTier]||gradeOrder[gradeOf(a)]-gradeOrder[gradeOf(b)]||b.score.total-a.score.total;
const gradeConclusion=(product:ScoredProduct)=>`${gradeOf(product)} · ${gradeLabels[gradeOf(product)]}`;
const formatImportedAt=(value:string|undefined)=>value?new Intl.DateTimeFormat("zh-CN",{year:"numeric",month:"2-digit",day:"2-digit",hour:"2-digit",minute:"2-digit",timeZone:"Asia/Shanghai"}).format(new Date(value)):"历史数据";
function saveFile(name:string,content:string,type="text/plain;charset=utf-8"){const a=document.createElement("a");a.href=URL.createObjectURL(new Blob([content],{type}));a.download=name;a.click();URL.revokeObjectURL(a.href)}
function blank():Product{return{asin:"",title:"",titleZh:"",imageUrl:"",importedAt:new Date().toISOString(),category:"客厅 / 边几",price:0,rating:0,reviews:0,bsr:99999,dimensions:"",weight:0,material:"",variants:"",sellingPoints:"",painPoints:"",sourceUrl:"",note:"",complexity:3,differentiation:3,returnRisk:"中"}}
function num(v:unknown){const match=String(v??"").replace(/,/g,"").match(/-?\d+(?:\.\d+)?/);return Number(match?.[0])||0}
function margin(v:unknown){const value=num(v);return value>0&&value<=1?value*100:value}
function sellerProduct(r:Record<string,unknown>):Product { const text=(v:unknown)=>String(v??""); const packageKg=num(r["包装重量（单位换算）"]); const title=text(r["商品标题"]); return {asin:text(r.ASIN),title,titleZh:chineseTitleFromRow(r),imageUrl:imageFromRow(r),importedAt:new Date().toISOString(),category:text(r["小类目"]||r["类目路径"]),price:num(r["价格($)"]),monthlySales:num(r["月销量"]),launchDays:num(r["上架天数"]),salesGrowth:num(r["销量环比增长率"]),packageGrossKg:packageKg,packageDimensionsCm:text(r["包装尺寸（单位换算）"]),rating:num(r["评分"]),reviews:num(r["评分数"]),bsr:num(r["小类BSR"]),dimensions:text(r["商品尺寸（单位换算）"]),weight:packageKg*2.205,material:text(r["详细参数"]),variants:text(r.SKU),sellingPoints:text(r["标签"]),painPoints:"",sourceUrl:text(r["商品详情页链接"]),note:text(r["品牌"]),complexity:3,differentiation:3,returnRisk:packageKg>49?"高":packageKg>22?"中":"低",estimatedMargin:margin(r["毛利率"]),priceUplift:3}; }

export default function Home(){
 const [tab,setTab]=useState("机会筛选"),[products,setProducts]=useState<Product[]>(samples),[editing,setEditing]=useState<Product|null>(null),[notice,setNotice]=useState("");
 const [favorites,setFavorites]=useState<Set<string>>(new Set()),[selected,setSelected]=useState<Set<string>>(new Set()),[hydrated,setHydrated]=useState(false),[compareOpen,setCompareOpen]=useState(false),[importMode,setImportMode]=useState<"replace"|"merge">("replace"),[opportunityTrack,setOpportunityTrack]=useState<OpportunityTrack>("red-ocean-blue");
 const [filters,setFilters]=useState({search:"",category:"全部",grade:"全部",minSales:0,sort:"grade"});
 useEffect(()=>{const id=window.setTimeout(()=>{if(new URLSearchParams(window.location.search).get("tab")==="calibration")setTab("校准模式")},0);return()=>window.clearTimeout(id)},[]);
 useEffect(()=>{const id=window.setTimeout(()=>{localStorage.removeItem("furniture-radar-v2");localStorage.removeItem("furniture-radar-v3");const raw=localStorage.getItem("furniture-radar-v4");if(raw)try{const d=JSON.parse(raw);setProducts(d.products??samples);setFavorites(new Set(d.favorites??[]))}catch{}setHydrated(true)},0);return()=>window.clearTimeout(id)},[]);
 useEffect(()=>{if(hydrated)localStorage.setItem("furniture-radar-v4",JSON.stringify({products,favorites:[...favorites]}))},[products,favorites,hydrated]);
 const scoredProducts=useMemo<ScoredProduct[]>(()=>products.map(p=>({...p,score:compute(p)})),[products]);
 const calibrationProducts=useMemo<BatchCalibrationCandidate[]>(()=>scoredProducts.map(p=>({asin:p.asin,title:p.title,titleZh:fullTitleZh(p.asin,p.titleZh),category:p.category,grade:gradeOf(p),score:p.score.total,interestTier:p.score.company.interestTier,imageUrl:p.imageUrl,sourceUrl:productUrl(p),price:p.price,monthlySales:p.monthlySales??0,reasons:p.score.reasons})),[scoredProducts]);
 const rows=useMemo(()=>scoredProducts.filter(p=>(filters.category==="全部"||p.category===filters.category)&&(filters.grade==="全部"||gradeOf(p)===filters.grade)&&(p.monthlySales??0)>=filters.minSales&&`${p.asin} ${p.title} ${fullTitleZh(p.asin,p.titleZh)}`.toLowerCase().includes(filters.search.toLowerCase())).sort((a,b)=>filters.sort==="sales"?(b.monthlySales??0)-(a.monthlySales??0):filters.sort==="growth"?(b.salesGrowth??0)-(a.salesGrowth??0):filters.sort==="margin"?b.score.company.estimatedMargin-a.score.company.estimatedMargin:recommendationOrder(a,b)),[scoredProducts,filters]);
 const recommended=useMemo(()=>scoredProducts.filter(p=>dataStatus(p)==="complete"&&(gradeOf(p)==="A"||gradeOf(p)==="B")).sort(recommendationOrder),[scoredProducts]);
 const gradeCounts=useMemo(()=>scoredProducts.reduce<Record<Grade,number>>((counts,p)=>{counts[gradeOf(p)]++;return counts},{A:0,B:0,C:0,D:0}),[scoredProducts]);
 const dataPendingRows=useMemo(()=>scoredProducts.filter(p=>dataStatus(p)==="needs_data"&&gradeOf(p)!=="D").sort((a,b)=>b.score.company.demand-a.score.company.demand),[scoredProducts]);
 const trackResult=(p:ScoredProduct)=>classifyOpportunityTrack(p,p.score.company);
 const trackCounts=useMemo(()=>scoredProducts.reduce<Record<OpportunityTrack,number>>((counts,p)=>{if(gradeOf(p)!=="D")counts[trackResult(p).track]++;return counts},{"red-ocean-blue":0,"blue-ocean-red":0,unmatched:0}),[scoredProducts]);
 const opportunityRows=useMemo(()=>rows.filter(p=>gradeOf(p)!=="D"&&trackResult(p).track===opportunityTrack).sort((a,b)=>trackResult(b).score-trackResult(a).score||recommendationOrder(a,b)),[rows,opportunityTrack]);
 const unmatchedRows=useMemo(()=>scoredProducts.filter(p=>gradeOf(p)!=="D"&&trackResult(p).track==="unmatched").sort(recommendationOrder),[scoredProducts]);
 const rejectedRows=useMemo(()=>scoredProducts.filter(p=>gradeOf(p)==="D").sort((a,b)=>b.score.company.demand-a.score.company.demand),[scoredProducts]);
 const potentialRows=useMemo(()=>scoredProducts.filter(p=>dataStatus(p)==="complete"&&gradeOf(p)!=="D"&&isPotentialProduct(p)).sort((a,b)=>potentialReasons(b).length-potentialReasons(a).length||b.score.total-a.score.total),[scoredProducts]);
 const favoriteRows=useMemo(()=>scoredProducts.filter(p=>favorites.has(p.asin)).sort(recommendationOrder),[scoredProducts,favorites]);
 const selectedRows=useMemo(()=>scoredProducts.filter(p=>selected.has(p.asin)),[scoredProducts,selected]);
 const cats=["全部",...Array.from(new Set(products.map(p=>p.category)))];
 const exportXlsx=async(output:ScoredProduct[],name="家具选品候选ASIN")=>{const XLSX=await import("xlsx");const header=[...fields.map(f=>labels[f]),"推荐等级","推荐结论","数据状态","预估利润率","利润可信度","风险与提示","已收藏"];const data=[header,...output.map(p=>{const pending=dataStatus(p)==="needs_data";return[...fields.map(f=>p[f]),pending?"":gradeOf(p),pending?"待补数据":gradeLabels[gradeOf(p)],pending?"数据待补":"数据完整",p.score.company.estimatedMargin,p.score.company.marginConfidence,[dataWarning(p),...p.score.reasons].filter(Boolean).join("；"),favorites.has(p.asin)?"是":"否"]})];const book=XLSX.utils.book_new();XLSX.utils.book_append_sheet(book,XLSX.utils.aoa_to_sheet(data),"选品清单");XLSX.writeFile(book,`${name}.xlsx`)};
 const exportCsv=(output:ScoredProduct[],name="家具选品清单")=>saveFile(`${name}.csv`,[[...fields.map(f=>labels[f]),"推荐等级","推荐结论","数据状态"].join(","),...output.map(p=>{const pending=dataStatus(p)==="needs_data";return[...fields.map(f=>p[f]),pending?"":gradeOf(p),pending?"待补数据":gradeLabels[gradeOf(p)],pending?"数据待补":"数据完整"].map(v=>`"${String(v??"").replaceAll('"','""')}"`).join(",")})].join("\n"),"text/csv;charset=utf-8");
 const toggleFavorite=(asin:string)=>setFavorites(old=>{const next=new Set(old);if(next.has(asin))next.delete(asin);else next.add(asin);return next});
 const toggleSelected=(asin:string)=>setSelected(old=>{const next=new Set(old);if(next.has(asin))next.delete(asin);else next.add(asin);return next});
 const selectVisible=(data:Product[],checked:boolean)=>setSelected(old=>{const next=new Set(old);data.forEach(p=>checked?next.add(p.asin):next.delete(p.asin));return next});
 const favoriteSelected=()=>{setFavorites(old=>new Set([...old,...selected]));setNotice(`已收藏 ${selected.size} 个产品。`)};
 const removeProducts=(asins:Set<string>)=>{if(!asins.size||!window.confirm(`确定删除 ${asins.size} 条产品记录吗？此操作无法撤销。`))return;setProducts(old=>old.filter(p=>!asins.has(p.asin)));setFavorites(old=>new Set([...old].filter(x=>!asins.has(x))));setSelected(old=>new Set([...old].filter(x=>!asins.has(x))));setNotice(`已删除 ${asins.size} 条记录。`)};
 const downloadTemplate=async()=>{const XLSX=await import("xlsx");const b=XLSX.utils.book_new();XLSX.utils.book_append_sheet(b,XLSX.utils.aoa_to_sheet([fields.map(f=>labels[f]),fields.map(f=>samples[0][f])]),"竞品数据");XLSX.writeFile(b,"家具选品导入模板.xlsx")};
 const importProducts=async(e:ChangeEvent<HTMLInputElement>)=>{const file=e.target.files?.[0];if(!file)return;try{const XLSX=await import("xlsx");const wb=XLSX.read(await file.arrayBuffer());const sheet=wb.Sheets[wb.SheetNames[0]];const raw=XLSX.utils.sheet_to_json<Record<string,unknown>>(sheet,{defval:""});attachSheetImageUrls(sheet,raw,XLSX);const isSellerSprite=Object.prototype.hasOwnProperty.call(raw[0]??{},"商品标题");const importedAt=new Date().toISOString();const incoming=(isSellerSprite?raw.map(sellerProduct):raw.map(r=>Object.fromEntries(fields.map(f=>[f,f==="imageUrl"?imageFromRow(r):r[labels[f]]??r[f]??""])) as unknown as Product)).filter(p=>p.asin&&p.title).map(p=>({...p,titleZh:String(p.titleZh||furnitureTitleZh(p.title)),importedAt,price:Number(p.price)||0,rating:Number(p.rating)||0,reviews:Number(p.reviews)||0,bsr:Number(p.bsr)||99999,weight:Number(p.weight)||0,monthlySales:Number(p.monthlySales)||0,launchDays:Number(p.launchDays)||9999,salesGrowth:Number(p.salesGrowth)||0,packageGrossKg:Number(p.packageGrossKg)||0,estimatedMargin:margin(p.estimatedMargin),priceUplift:Number(p.priceUplift)||3,complexity:Number(p.complexity)||3,differentiation:Number(p.differentiation)||3,returnRisk:["低","中","高"].includes(String(p.returnRisk))?p.returnRisk:"中" as Risk}));if(!incoming.length)throw Error();const imageCount=incoming.filter(p=>p.imageUrl).length;if(importMode==="replace"){if(!window.confirm(`将用 ${incoming.length} 条新数据替换当前 ${products.length} 条产品，收藏和已选记录也会清空。确定继续吗？`))return;setProducts(incoming);setFavorites(new Set());setSelected(new Set())}else setProducts(old=>{const map=new Map(old.map(p=>[p.asin,p]));incoming.forEach(p=>map.set(p.asin,p));return[...map.values()]});setNotice(`已${importMode==="replace"?"替换为":"追加"} ${incoming.length} 条产品，其中自动识别主图 ${imageCount} 张，导入时间 ${formatImportedAt(importedAt)}。`)}catch{setNotice("导入失败：请使用模板列名，并确认 ASIN 和英文标题已填写。")}finally{e.target.value=""}};
 const save=()=>{if(!editing?.asin||!editing.title)return setNotice("请至少填写 ASIN 和英文标题。");setProducts(old=>{const i=old.findIndex(p=>p.asin===editing.asin);return i<0?[editing,...old]:old.map((p,n)=>n===i?editing:p)});setEditing(null);setNotice("记录已保存。")};
 return <><main><header><div><span className="eyebrow">AI PRODUCT INTELLIGENCE · AMAZON US</span><h1 className="brand">LIN<span>X</span></h1><p>家具机会识别工作台 · {products.length} 个真实 ASIN，按公司适配、市场信号与差异化空间进行初筛排序。</p></div><div className="header-score"><b>{scoredProducts.filter(p=>gradeOf(p)!=="D").length}</b><span>个进入初筛排名</span></div></header>
 <nav>{["机会筛选","方向不匹配","校准模式","潜力款","候选 ASIN","数据待补","不推荐","数据管理","收藏夹","推荐规则"].map(x=><button key={x} className={tab===x?"active":""} onClick={()=>setTab(x)}>{x}{x==="方向不匹配"&&unmatchedRows.length>0?<em>{unmatchedRows.length}</em>:x==="校准模式"?<em>批量</em>:x==="潜力款"&&potentialRows.length>0?<em>{potentialRows.length}</em>:x==="数据待补"&&dataPendingRows.length>0?<em>{dataPendingRows.length}</em>:x==="不推荐"?<em>{rejectedRows.length}</em>:x==="收藏夹"&&favorites.size>0?<em>{favorites.size}</em>:null}</button>)}</nav>{notice&&<div className="toast">{notice}<button onClick={()=>setNotice("")}>×</button></div>}
  {tab==="机会筛选"&&<><section className="hero"><div><span className="tag">DUAL OPPORTUNITY MODEL</span><h2>两条开发赛道，分别排名</h2><p>成熟柜类寻找造型元素创新；小众场景寻找已经出现真实需求、但仍有进入空间的细分类目。两类产品不再使用同一顺序混排。</p></div><div className="grade-summary">{(["A","B","C","D"] as Grade[]).map(grade=><button key={grade} onClick={()=>grade==="D"?setTab("不推荐"):setFilters({...filters,grade})}><b className={`grade grade-${grade}`}>{grade}</b><span>{gradeLabels[grade]} · {gradeCounts[grade]} 个</span></button>)}</div></section><OpportunityTracks active={opportunityTrack} setActive={setOpportunityTrack} counts={trackCounts}/><section className="filters"><input placeholder="搜索 ASIN 或英文标题" value={filters.search} onChange={e=>setFilters({...filters,search:e.target.value})}/><select value={filters.category} onChange={e=>setFilters({...filters,category:e.target.value})}>{cats.map(x=><option key={x}>{x}</option>)}</select><select value={filters.grade} onChange={e=>setFilters({...filters,grade:e.target.value})}>{["全部","A","B","C"].map(x=><option key={x}>{x==="全部"?"全部推荐等级":`${x} · ${gradeLabels[x as Grade]}`}</option>)}</select><label>最低月销 <input type="number" value={filters.minSales||""} placeholder="不限" onChange={e=>setFilters({...filters,minSales:Number(e.target.value)||0})}/></label><select value={filters.sort} onChange={e=>setFilters({...filters,sort:e.target.value})}><option value="grade">赛道机会分排序</option><option value="sales">月销量排序</option><option value="growth">增长率排序</option><option value="margin">利润率排序</option></select><button className="quiet" onClick={()=>setFilters({search:"",category:"全部",grade:"全部",minSales:0,sort:"grade"})}>重置</button></section><BulkBar data={opportunityRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Cards rows={opportunityRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></>}
  {tab==="方向不匹配"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">OUTSIDE CURRENT STRATEGY</span><h2>方向不匹配</h2><p>这些产品没有触发硬性淘汰，但目前既缺少成熟柜类的明确造型创新，也没有足够清晰的小众使用场景，因此不进入两条机会榜。</p></div><span className="tag">{unmatchedRows.length} 个</span></div><Cards rows={unmatchedRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
  {tab==="校准模式"&&<BatchCalibrationPanel products={calibrationProducts}/>}
 {tab==="潜力款"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">EARLY OPPORTUNITIES</span><h2>潜力款</h2><p>上架不超过 180 天、月销 50–300、单 Listing 评论少于 100，并出现增长、造型或改款信号；月销超过 300 已属于爆款。</p></div><span className="tag">{potentialRows.length} 个潜力信号</span></div><BulkBar data={potentialRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"潜力款已选")} compare={()=>setCompareOpen(true)}/><Cards rows={potentialRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="数据待补"&&<section className="panel data-pending-panel"><div className="section-title"><div><span className="eyebrow">DATA REQUIRED</span><h2>数据待补</h2><p>这些商品会参与初筛排序，但在包装、材质、销量和上架时间补齐前，不形成正式 A / B / C 结论，也不会因为缺数据直接判 D。</p></div><span className="tag">{dataPendingRows.length} 个待补记录</span></div><BulkBar data={dataPendingRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"数据待补产品")} compare={()=>setCompareOpen(true)}/><Cards rows={dataPendingRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="数据管理"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">DATA INTAKE</span><h2>竞品数据管理</h2><p>当前为亚马逊美国站自主调研的 {products.length} 个不重复 ASIN，主图与 Listing 链接完整。</p></div><div className="actions"><select value={importMode} onChange={e=>setImportMode(e.target.value as "replace"|"merge")}><option value="replace">导入后替换当前批次</option><option value="merge">追加并更新重复 ASIN</option></select><button onClick={downloadTemplate}>下载 XLSX 模板</button><label className="primary file">导入 CSV / XLSX<input type="file" accept=".csv,.xlsx,.xls" onChange={importProducts}/></label><button onClick={()=>setEditing(blank())}>+ 新增记录</button></div></div>{editing?<Form product={editing} set={setEditing} save={save} cancel={()=>setEditing(null)}/>:<><BulkBar data={products} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)} removeSelected={()=>removeProducts(selected)}/><Table data={products} edit={setEditing} remove={asin=>removeProducts(new Set([asin]))} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></>}</section>}
 {tab==="候选 ASIN"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">SHORTLIST</span><h2>候选 ASIN 清单</h2><p>仅显示通过公司适配、物流与利润预测筛选的记录。</p></div><div className="actions"><button onClick={()=>exportCsv(selectedRows.length?selectedRows:recommended,"家具选品候选ASIN")}>导出 CSV</button><button className="primary" onClick={()=>exportXlsx(selectedRows.length?selectedRows:recommended)}>导出 Excel</button></div></div><BulkBar data={recommended} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Table data={recommended} edit={p=>{setEditing(p);setTab("数据管理")}} remove={()=>{}} showScore selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="不推荐"&&<section className="panel rejected-panel"><div className="section-title"><div><span className="eyebrow">NOT RECOMMENDED</span><h2>D 档 · 不推荐产品</h2><p>这里只包含已确认触发硬性淘汰条件的产品，例如供应链不匹配、确定超出物流能力、售价或利润低于门槛；卡片会显示具体原因。</p></div><span className="tag">{rejectedRows.length} 个已确认淘汰</span></div><BulkBar data={rejectedRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"不推荐产品")} compare={()=>setCompareOpen(true)}/><Cards rows={rejectedRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="收藏夹"&&<section className="panel"><div className="section-title"><div><span className="eyebrow">FAVORITES</span><h2>产品收藏夹</h2><p>红心产品会一直保存在当前浏览器，可多选比较或导出。</p></div><button className="primary" disabled={!favoriteRows.length} onClick={()=>exportXlsx(favoriteRows,"收藏产品")}>导出收藏</button></div><BulkBar data={favoriteRows} selected={selected} selectVisible={selectVisible} favoriteSelected={favoriteSelected} exportSelected={()=>exportXlsx(selectedRows,"已选产品")} compare={()=>setCompareOpen(true)}/><Cards rows={favoriteRows} edit={p=>{setEditing(p);setTab("数据管理")}} selected={selected} favorites={favorites} toggleSelected={toggleSelected} toggleFavorite={toggleFavorite}/></section>}
 {tab==="推荐规则"&&<Settings products={products} setProducts={setProducts} favorites={favorites} setFavorites={setFavorites} notice={setNotice}/>}</main>
 {compareOpen&&<CompareDrawer products={selectedRows.slice(0,4)} close={()=>setCompareOpen(false)}/>}
 </>;
}
function BulkBar({data,selected,selectVisible,favoriteSelected,exportSelected,compare,removeSelected}:{data:Product[];selected:Set<string>;selectVisible:(data:Product[],checked:boolean)=>void;favoriteSelected:()=>void;exportSelected:()=>void;compare:()=>void;removeSelected?:()=>void}){const visibleSelected=data.filter(p=>selected.has(p.asin)).length;const allSelected=data.length>0&&visibleSelected===data.length;return <div className="bulk-bar"><label><input type="checkbox" checked={allSelected} onChange={e=>selectVisible(data,e.target.checked)}/><span>{allSelected?"取消全选":"选择当前结果"}</span></label><span className="result-count">{data.length} 个结果</span>{selected.size>0&&<div className="bulk-actions"><b>已选 {selected.size}</b><button onClick={favoriteSelected}>♥ 批量收藏</button><button onClick={compare}>并排对比</button><button onClick={exportSelected}>导出已选</button>{removeSelected&&<button className="danger-action" onClick={removeSelected}>删除已选</button>}</div>}</div>}
function ProductVisual({product}:{product:Product}){const[failed,setFailed]=useState(false);return <div className="product-visual"><span aria-hidden="true">▱</span>{product.imageUrl&&!failed&&<img src={product.imageUrl} alt={product.title} loading="lazy" onError={()=>setFailed(true)}/>}<small>{failed?"主图暂时无法加载":product.imageUrl?"":"导入主图后显示"}</small></div>}
function productUrl(product:Product){const source=product.sourceUrl?.trim();if(source)return source;return/^[A-Z0-9]{10}$/i.test(product.asin)?`https://www.amazon.com/dp/${product.asin}`:`https://www.amazon.com/s?k=${encodeURIComponent(product.title)}`}
function ProductTitle({product}:{product:Product}){return <><a href={productUrl(product)} target="_blank" rel="noreferrer" title="打开 Amazon Listing">{product.title}<span className="external">↗</span></a><span className="title-zh">{fullTitleZh(product.asin,product.titleZh)}</span></>}
function OpportunityTracks({active,setActive,counts}:{active:OpportunityTrack;setActive:(track:OpportunityTrack)=>void;counts:Record<OpportunityTrack,number>}){const tracks:[OpportunityTrack,string,string,string][]=[["red-ocean-blue","红海中的蓝海","成熟柜类 · 元素造型创新","餐边柜、橱柜、书柜等成熟市场，重点看拱形、波纹、藤编和异形结构。"],["blue-ocean-red","蓝海中的红海","小众类目 · 场景功能机会","爬宠箱、洗衣机工作台、美甲桌、商业前台、隐藏垃圾柜等细分场景。"]];return <section className="track-switcher">{tracks.map(([id,title,subtitle,description])=><button key={id} className={active===id?"active":""} onClick={()=>setActive(id)}><span>{subtitle}</span><b>{title}</b><p>{description}</p><em>{counts[id]} 款符合</em></button>)}</section>}
function Cards({rows,edit,selected,favorites,toggleSelected,toggleFavorite}:{rows:ScoredProduct[];edit:(p:Product)=>void;selected:Set<string>;favorites:Set<string>;toggleSelected:(asin:string)=>void;toggleFavorite:(asin:string)=>void}){
 return <section className="cards">{rows.map(p=>{
  const potential=isPotentialProduct(p),warning=dataWarning(p),grade=gradeOf(p);
  return <article className={`card ${selected.has(p.asin)?"selected":""}`} key={p.asin} tabIndex={0}><div className="card-select"><label title="选择产品"><input type="checkbox" checked={selected.has(p.asin)} onChange={()=>toggleSelected(p.asin)}/></label><button className={`heart ${favorites.has(p.asin)?"active":""}`} onClick={()=>toggleFavorite(p.asin)} aria-label={favorites.has(p.asin)?"取消收藏":"收藏产品"}>♥</button></div><ProductVisual product={p}/><div className="card-body"><div className="card-top"><div className="card-labels">{warning&&<span className="data-status-badge">数据待补</span>}{potential&&<span className="potential-badge">潜力款</span>}</div><strong className={`grade grade-${warning?"C":grade}`}>{warning?"待补":grade}<small>{warning?"数据":gradeLabels[grade]}</small></strong></div><span className="category">{p.category}</span><h3><ProductTitle product={p}/></h3><p className="asin">{p.asin}</p><div className="quick-stats"><div><b>${p.price}</b><span>售价</span></div><div><b>{compact(p.monthlySales??0)}</b><span>月销</span></div><div><b className={(p.salesGrowth??0)>0?"up":""}>{(p.salesGrowth??0)>0?"+":""}{percent(p.salesGrowth)}</b><span>增长</span></div><div><b>{percent(p.score.company.estimatedMargin)}</b><span>利润</span></div></div><div className="card-details"><div className="detail-grid"><span><b>★ {p.rating||"—"}</b>评分 · {compact(p.reviews)} 评论</span><span><b>{withUnit(p.packageGrossKg,"kg")}</b>包装毛重</span><span><b>{p.bsr>0?`#${compact(p.bsr)}`:"—"}</b>类目 BSR</span><span><b>{withUnit(p.launchDays,"天")}</b>上架时间</span><span><b>{formatImportedAt(p.importedAt)}</b>导入时间</span></div><div className="meter"><i style={{width:p.score.dev+"%"}}/></div><p className="opportunity">{potential?`潜力信号：${potentialReasons(p).join("、")}`:p.score.company.affinity.length?`匹配方向：${p.score.company.affinity.join("、")}`:p.score.company.trendElements.length?`机会元素：${p.score.company.trendElements.join("、")}`:p.note||"待补充改款方向"}</p><p className={warning?"reason data-warning":"reason"}>{warning||(p.score.reasons.length?p.score.reasons.slice(0,2).join(" · "):"物流与开发风险可控")}</p></div><div className="card-bottom"><span>{p.score.company.categoryVerdict}</span><button onClick={()=>edit(p)}>完整数据 →</button></div></div></article>
 })}{!rows.length&&<div className="empty"><b>这里暂时没有产品</b><span>调整筛选条件，或在商品卡上点击红心加入收藏。</span></div>}</section>
}
function Table({data,edit,remove,showScore=false,selected,favorites,toggleSelected,toggleFavorite}:{data:(Product|ScoredProduct)[];edit:(p:Product)=>void;remove:(asin:string)=>void;showScore?:boolean;selected:Set<string>;favorites:Set<string>;toggleSelected:(asin:string)=>void;toggleFavorite:(asin:string)=>void}){return <div className="table-wrap"><table><thead><tr><th className="check-col"></th><th>ASIN / 商品</th><th>类目</th><th>价格</th><th>月销</th><th>导入时间</th><th>风险</th><th>数据状态</th>{showScore&&<th>推荐结论</th>}<th>操作</th></tr></thead><tbody>{data.map(p=><tr key={p.asin} className={selected.has(p.asin)?"selected-row":""}><td><input type="checkbox" checked={selected.has(p.asin)} onChange={()=>toggleSelected(p.asin)}/></td><td><div className="table-product"><button className={`heart ${favorites.has(p.asin)?"active":""}`} onClick={()=>toggleFavorite(p.asin)}>♥</button><div><b>{p.asin}</b><span><ProductTitle product={p}/></span></div></div></td><td>{p.category}</td><td>${p.price}</td><td>{compact(p.monthlySales??0)}</td><td>{formatImportedAt(p.importedAt)}</td><td><span className={`risk risk-${p.returnRisk}`}>{p.returnRisk}</span></td><td><span className={dataStatus(p)==="needs_data"?"data-status-badge":"data-status-ok"}>{dataStatus(p)==="needs_data"?"数据待补":"数据完整"}</span></td>{showScore&&<td>{"score" in p?<b className={`grade grade-${gradeOf(p)}`}>{gradeConclusion(p)}</b>:"—"}</td>}<td><button className="link" onClick={()=>edit(p)}>编辑</button>{!showScore&&<button className="danger" onClick={()=>remove(p.asin)}>删除</button>}</td></tr>)}</tbody></table>{!data.length&&<div className="empty table-empty"><b>暂无记录</b></div>}</div>}
function CompareDrawer({products,close}:{products:ScoredProduct[];close:()=>void}){return <div className="modal-backdrop" onMouseDown={e=>{if(e.target===e.currentTarget)close()}}><section className="compare-modal"><div className="compare-head"><div><span className="eyebrow">PRODUCT COMPARISON</span><h2>产品并排对比</h2><p>一次最多展示前 4 个已选产品。</p></div><button onClick={close}>关闭</button></div>{products.length?<div className="compare-grid"><div className="compare-labels"><b>产品</b><span>推荐结论</span><span>售价 / 月销</span><span>增长 / 评论</span><span>利润率</span><span>包装毛重</span><span>数据状态</span></div>{products.map(p=>{const grade=gradeOf(p),warning=dataWarning(p);return <div className="compare-column" key={p.asin}><div><ProductVisual product={p}/><h3><ProductTitle product={p}/></h3><small>{p.asin}</small></div><strong className={`grade grade-${warning?"C":grade}`}>{warning?"待补":grade}<small>{warning?"数据":gradeLabels[grade]}</small></strong><span>${p.price} / {compact(p.monthlySales??0)}</span><span>{percent(p.salesGrowth)} / {compact(p.reviews)}</span><span>{percent(p.score.company.estimatedMargin)}</span><span>{withUnit(p.packageGrossKg,"kg")}</span><span className={warning?"data-status-badge":"data-status-ok"}>{warning||"数据完整"}</span></div>})}</div>:<div className="empty"><b>请先选择产品</b><span>在商品卡或表格中勾选 2—4 个产品后再对比。</span></div>}</section></div>}
function Form({product,set,save,cancel}:{product:Product;set:(p:Product)=>void;save:()=>void;cancel:()=>void}){const numeric=["price","monthlySales","launchDays","salesGrowth","estimatedMargin","packageGrossKg","priceUplift","rating","reviews","bsr","weight","complexity","differentiation"];return <div className="form">{fields.map(f=><label key={f} className={["title","titleZh","imageUrl","sellingPoints","painPoints","note","sourceUrl","packageDimensionsCm"].includes(f)?"wide":""}>{labels[f]}{["sellingPoints","painPoints","note"].includes(f)?<textarea value={String(product[f]??"")} onChange={e=>set({...product,[f]:e.target.value})}/>:f==="returnRisk"?<select value={product.returnRisk} onChange={e=>set({...product,returnRisk:e.target.value as Risk})}>{["低","中","高"].map(x=><option key={x}>{x}</option>)}</select>:<input type={numeric.includes(f)?"number":"text"} value={String(product[f]??"")} placeholder={f==="titleZh"?furnitureTitleZh(product.title):undefined} onChange={e=>set({...product,[f]:numeric.includes(f)?Number(e.target.value):e.target.value})}/>}</label>)}<div className="form-actions"><button onClick={cancel}>取消</button><button className="primary" onClick={save}>保存记录</button></div></div>}
function Settings({products,setProducts,favorites,setFavorites,notice}:{products:Product[];setProducts:(p:Product[])=>void;favorites:Set<string>;setFavorites:(p:Set<string>)=>void;notice:(s:string)=>void}){const rules=[["新品标准","上架不超过 180 天"],["早期验证","月销 50–300"],["爆款阶段","月销超过 300"],["评论壁垒","单 Listing 评论少于 100"],["目标价格","最低售价 100 美元"],["利润中线","20%，按可信度渐进加减分"],["包装数据","仅用于利润估算与数据完整性"]];const restore=async(e:ChangeEvent<HTMLInputElement>)=>{const f=e.target.files?.[0];if(!f)return;try{const d=JSON.parse(await f.text());if(!Array.isArray(d.products))throw Error();setProducts(d.products);setFavorites(new Set(d.favorites??[]));if(d.calibration)localStorage.setItem("linx-calibration-v1",JSON.stringify(d.calibration));if(d.batchCalibration)localStorage.setItem("linx-batch-calibration-v1",JSON.stringify(d.batchCalibration));notice("备份已恢复。")}catch{notice("备份文件无效。")}e.target.value=""};const backup=()=>{let calibration=null,batchCalibration=null;try{calibration=JSON.parse(localStorage.getItem("linx-calibration-v1")||"null");batchCalibration=JSON.parse(localStorage.getItem("linx-batch-calibration-v1")||"null")}catch{}saveFile("家具选品备份.json",JSON.stringify({products,favorites:[...favorites],calibration,batchCalibration},null,2),"application/json")};return <section className="panel settings"><div><span className="eyebrow">RECOMMENDATION RULES</span><h2>统一推荐规则</h2><p>核心参数由模型集中维护，普通用户无需频繁调整；“数据待补”独立于 A、B、C、D 结论。</p></div><div className="grade-guide"><span className="grade grade-A">A<small>值得开发</small></span><span className="grade grade-B">B<small>继续调研</small></span><span className="grade grade-C">C<small>暂缓</small></span><span className="grade grade-D">D<small>不推荐</small></span></div><div className="weight-grid">{rules.map(([name,detail])=><div className="weight" key={name}><span>{name}<small>{detail}</small></span></div>)}</div><hr/><div className="backup"><div><h3>本地数据备份</h3><p>产品数据、收藏夹和两阶段校准反馈会一起备份。更换电脑前请下载。</p></div><div className="actions"><button onClick={backup}>下载 JSON 备份</button><label className="file">恢复备份<input type="file" accept=".json" onChange={restore}/></label></div></div></section>}
